// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xai/shared/analytics/analytics.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// This file defines a generic interface for aggregating numeric data stored in clickhouse.
// The result is a set of time series (one per value and group) over a fixed time window.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Time series are created by aggregating value into buckets we call `TimeUnit`.
public enum Prod_ClickhouseAnalytics_TimeUnit: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case invalid // = 0
  case month // = 1
  case calendarWeek // = 2
  case day // = 3
  case hour // = 4
  case quarterHour // = 5
  case minute // = 6
  case second // = 7

  /// None means having one single time bucket for all events.
  /// This can be used to count total number of events ever for example.
  case none // = 8
  case UNRECOGNIZED(Int)

  public init() {
    self = .invalid
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .invalid
    case 1: self = .month
    case 2: self = .calendarWeek
    case 3: self = .day
    case 4: self = .hour
    case 5: self = .quarterHour
    case 6: self = .minute
    case 7: self = .second
    case 8: self = .none
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .invalid: return 0
    case .month: return 1
    case .calendarWeek: return 2
    case .day: return 3
    case .hour: return 4
    case .quarterHour: return 5
    case .minute: return 6
    case .second: return 7
    case .none: return 8
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Prod_ClickhouseAnalytics_TimeUnit] = [
    .invalid,
    .month,
    .calendarWeek,
    .day,
    .hour,
    .quarterHour,
    .minute,
    .second,
    .none,
  ]

}

/// Each value is an aggregate of the individual values in the time bucket. Note that not every field
/// supports every aggregation method.
public enum Prod_ClickhouseAnalytics_Aggregation: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case none // = 0
  case sum // = 1
  case avg // = 2
  case `var` // = 3
  case std // = 4
  case min // = 5
  case max // = 6
  case p50 // = 7
  case p90 // = 8
  case p99 // = 9
  case p999 // = 10
  case count // = 11
  case countDistinct // = 12
  case UNRECOGNIZED(Int)

  public init() {
    self = .none
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .none
    case 1: self = .sum
    case 2: self = .avg
    case 3: self = .var
    case 4: self = .std
    case 5: self = .min
    case 6: self = .max
    case 7: self = .p50
    case 8: self = .p90
    case 9: self = .p99
    case 10: self = .p999
    case 11: self = .count
    case 12: self = .countDistinct
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .none: return 0
    case .sum: return 1
    case .avg: return 2
    case .var: return 3
    case .std: return 4
    case .min: return 5
    case .max: return 6
    case .p50: return 7
    case .p90: return 8
    case .p99: return 9
    case .p999: return 10
    case .count: return 11
    case .countDistinct: return 12
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Prod_ClickhouseAnalytics_Aggregation] = [
    .none,
    .sum,
    .avg,
    .var,
    .std,
    .min,
    .max,
    .p50,
    .p90,
    .p99,
    .p999,
    .count,
    .countDistinct,
  ]

}

/// Allows the user to specify a time range in their local timezone.
public struct Prod_ClickhouseAnalytics_TimeRange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The from-time in the format YYYY-MM-DD HH:MM:SS.
  public var startTime: String = String()

  /// The to-time in the format YYYY-MM-DD HH:MM:SS (not including).
  public var endTime: String = String()

  /// The timezone that all timestamps are reported in.
  /// The timezone must be represented by the IANA time zone identifier (e.g. America/New_York).
  public var timezone: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Determines which values shall be measured and how they shall be aggregated.
public struct Prod_ClickhouseAnalytics_Value: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Name of the field to measure.
  public var name: String = String()

  /// Aggregation method to use.
  public var aggregation: Prod_ClickhouseAnalytics_Aggregation = .none

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request body for analytics.
public struct Prod_ClickhouseAnalytics_AnalyticsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The range over which to return the time series.
  public var timeRange: Prod_ClickhouseAnalytics_TimeRange {
    get {_timeRange ?? Prod_ClickhouseAnalytics_TimeRange()}
    set {_timeRange = newValue}
  }
  /// Returns true if `timeRange` has been explicitly set.
  public var hasTimeRange: Bool {self._timeRange != nil}
  /// Clears the value of `timeRange`. Subsequent reads from it will return its default value.
  public mutating func clearTimeRange() {self._timeRange = nil}

  /// The granularity of the returned aggregation.
  public var timeUnit: Prod_ClickhouseAnalytics_TimeUnit = .invalid

  /// Name of the fields to aggregate.
  public var values: [Prod_ClickhouseAnalytics_Value] = []

  /// For each value of the group-by tuple, we return one time series.
  public var groupBy: [String] = []

  /// A conditions that filter the individual log items, which get analyzed.
  /// Syntax:
  /// (NOT) [field]:[operator][value] (AND|OR)
  /// Example:
  ///  api_key_id:0000-9999-9999-9999
  ///  usage:>100
  ///
  /// All filter conditions are combined using AND.
  public var filters: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _timeRange: Prod_ClickhouseAnalytics_TimeRange? = nil
}

/// Response body for analytics.
public struct Prod_ClickhouseAnalytics_AnalyticsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// For each value of the group-by clause, we return one time series.
  public var timeSeries: [Prod_ClickhouseAnalytics_TimeSeries] = []

  /// If this is true, the maximum cardinality of the query has been reached and only a subset of
  /// results is returned.
  public var limitReached: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A time series is a sequence of values.
public struct Prod_ClickhouseAnalytics_TimeSeries: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Values of the fields that were grouped by.
  public var group: [String] = []

  /// Values to group the time series by.
  public var groupLabels: [String] = []

  /// Data points ordered by timestamp. Data points are dense in the range provided (meaning we
  /// return one data point for every interval in the requested time range).
  public var dataPoints: [Prod_ClickhouseAnalytics_DataPoint] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Prod_ClickhouseAnalytics_DataPoint: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The timestamp (in UTC) when the data point was recorded.
  public var timestamp: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_timestamp ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  public var hasTimestamp: Bool {self._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimestamp() {self._timestamp = nil}

  /// The values that were recorded at that datapoint.
  public var values: [Double] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _timestamp: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// The analytics scheme specifies which fields can be measured, group by, and filtered by.
public struct Prod_ClickhouseAnalytics_AnalyticsScheme: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of values that can be measured.
  public var values: [Prod_ClickhouseAnalytics_ValueScheme] = []

  /// List of fields that can be filtered by.
  public var filters: [String] = []

  /// List of fields that can be grouped by.
  public var groupBy: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Specifies a value and which aggregation methods it supports.
public struct Prod_ClickhouseAnalytics_ValueScheme: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var aggregations: [Prod_ClickhouseAnalytics_Aggregation] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Prod_ClickhouseAnalytics_StringRawValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var value: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Prod_ClickhouseAnalytics_FloatRawValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var value: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Generic representation of a Clickhouse row.
public struct Prod_ClickhouseAnalytics_AnalyticsRow: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique identifier for this log item. May or may not
  /// represent anything else in the system.
  public var logID: String = String()

  /// Values for numerical columns in the log.
  public var values: [Prod_ClickhouseAnalytics_FloatRawValue] = []

  /// String values coming from the group-by fields.
  public var groupByValues: [Prod_ClickhouseAnalytics_StringRawValue] = []

  /// String values coming from the filter-by fields.
  /// This is NOT deduplicated from `group_by_values`
  /// in case a column can be a filter and a group-by.
  public var filterByValues: [Prod_ClickhouseAnalytics_StringRawValue] = []

  /// The UTC timestamp when the data was recorded.
  public var timestamp: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_timestamp ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_timestamp = newValue}
  }
  /// Returns true if `timestamp` has been explicitly set.
  public var hasTimestamp: Bool {self._timestamp != nil}
  /// Clears the value of `timestamp`. Subsequent reads from it will return its default value.
  public mutating func clearTimestamp() {self._timestamp = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _timestamp: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "prod.clickhouse_analytics"

extension Prod_ClickhouseAnalytics_TimeUnit: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TIME_UNIT_INVALID\0\u{1}TIME_UNIT_MONTH\0\u{1}TIME_UNIT_CALENDAR_WEEK\0\u{1}TIME_UNIT_DAY\0\u{1}TIME_UNIT_HOUR\0\u{1}TIME_UNIT_QUARTER_HOUR\0\u{1}TIME_UNIT_MINUTE\0\u{1}TIME_UNIT_SECOND\0\u{1}TIME_UNIT_NONE\0")
}

extension Prod_ClickhouseAnalytics_Aggregation: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AGGREGATION_NONE\0\u{1}AGGREGATION_SUM\0\u{1}AGGREGATION_AVG\0\u{1}AGGREGATION_VAR\0\u{1}AGGREGATION_STD\0\u{1}AGGREGATION_MIN\0\u{1}AGGREGATION_MAX\0\u{1}AGGREGATION_P50\0\u{1}AGGREGATION_P90\0\u{1}AGGREGATION_P99\0\u{1}AGGREGATION_P999\0\u{1}AGGREGATION_COUNT\0\u{1}AGGREGATION_COUNT_DISTINCT\0")
}

extension Prod_ClickhouseAnalytics_TimeRange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TimeRange"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_time\0\u{3}end_time\0\u{1}timezone\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.startTime) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.endTime) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.timezone) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.startTime.isEmpty {
      try visitor.visitSingularStringField(value: self.startTime, fieldNumber: 1)
    }
    if !self.endTime.isEmpty {
      try visitor.visitSingularStringField(value: self.endTime, fieldNumber: 2)
    }
    if !self.timezone.isEmpty {
      try visitor.visitSingularStringField(value: self.timezone, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_TimeRange, rhs: Prod_ClickhouseAnalytics_TimeRange) -> Bool {
    if lhs.startTime != rhs.startTime {return false}
    if lhs.endTime != rhs.endTime {return false}
    if lhs.timezone != rhs.timezone {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_Value: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Value"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}aggregation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.aggregation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.aggregation != .none {
      try visitor.visitSingularEnumField(value: self.aggregation, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_Value, rhs: Prod_ClickhouseAnalytics_Value) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.aggregation != rhs.aggregation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_AnalyticsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnalyticsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}time_range\0\u{3}time_unit\0\u{1}values\0\u{3}group_by\0\u{1}filters\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._timeRange) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.timeUnit) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.groupBy) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.filters) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._timeRange {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.timeUnit != .invalid {
      try visitor.visitSingularEnumField(value: self.timeUnit, fieldNumber: 2)
    }
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 3)
    }
    if !self.groupBy.isEmpty {
      try visitor.visitRepeatedStringField(value: self.groupBy, fieldNumber: 4)
    }
    if !self.filters.isEmpty {
      try visitor.visitRepeatedStringField(value: self.filters, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_AnalyticsRequest, rhs: Prod_ClickhouseAnalytics_AnalyticsRequest) -> Bool {
    if lhs._timeRange != rhs._timeRange {return false}
    if lhs.timeUnit != rhs.timeUnit {return false}
    if lhs.values != rhs.values {return false}
    if lhs.groupBy != rhs.groupBy {return false}
    if lhs.filters != rhs.filters {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_AnalyticsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnalyticsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}time_series\0\u{3}limit_reached\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.timeSeries) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.limitReached) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.timeSeries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.timeSeries, fieldNumber: 1)
    }
    if self.limitReached != false {
      try visitor.visitSingularBoolField(value: self.limitReached, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_AnalyticsResponse, rhs: Prod_ClickhouseAnalytics_AnalyticsResponse) -> Bool {
    if lhs.timeSeries != rhs.timeSeries {return false}
    if lhs.limitReached != rhs.limitReached {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_TimeSeries: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TimeSeries"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}group\0\u{3}data_points\0\u{3}group_labels\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.group) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.dataPoints) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.groupLabels) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.group.isEmpty {
      try visitor.visitRepeatedStringField(value: self.group, fieldNumber: 1)
    }
    if !self.dataPoints.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.dataPoints, fieldNumber: 2)
    }
    if !self.groupLabels.isEmpty {
      try visitor.visitRepeatedStringField(value: self.groupLabels, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_TimeSeries, rhs: Prod_ClickhouseAnalytics_TimeSeries) -> Bool {
    if lhs.group != rhs.group {return false}
    if lhs.groupLabels != rhs.groupLabels {return false}
    if lhs.dataPoints != rhs.dataPoints {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_DataPoint: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DataPoint"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}timestamp\0\u{1}values\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._timestamp) }()
      case 2: try { try decoder.decodeRepeatedDoubleField(value: &self.values) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._timestamp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.values.isEmpty {
      try visitor.visitPackedDoubleField(value: self.values, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_DataPoint, rhs: Prod_ClickhouseAnalytics_DataPoint) -> Bool {
    if lhs._timestamp != rhs._timestamp {return false}
    if lhs.values != rhs.values {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_AnalyticsScheme: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnalyticsScheme"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}values\0\u{1}filters\0\u{3}group_by\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.filters) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.groupBy) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 1)
    }
    if !self.filters.isEmpty {
      try visitor.visitRepeatedStringField(value: self.filters, fieldNumber: 2)
    }
    if !self.groupBy.isEmpty {
      try visitor.visitRepeatedStringField(value: self.groupBy, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_AnalyticsScheme, rhs: Prod_ClickhouseAnalytics_AnalyticsScheme) -> Bool {
    if lhs.values != rhs.values {return false}
    if lhs.filters != rhs.filters {return false}
    if lhs.groupBy != rhs.groupBy {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_ValueScheme: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ValueScheme"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}aggregations\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeRepeatedEnumField(value: &self.aggregations) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.aggregations.isEmpty {
      try visitor.visitPackedEnumField(value: self.aggregations, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_ValueScheme, rhs: Prod_ClickhouseAnalytics_ValueScheme) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.aggregations != rhs.aggregations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_StringRawValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StringRawValue"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_StringRawValue, rhs: Prod_ClickhouseAnalytics_StringRawValue) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_FloatRawValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FloatRawValue"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.value.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.value, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_FloatRawValue, rhs: Prod_ClickhouseAnalytics_FloatRawValue) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Prod_ClickhouseAnalytics_AnalyticsRow: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AnalyticsRow"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}log_id\0\u{1}values\0\u{3}group_by_values\0\u{3}filter_by_values\0\u{1}timestamp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.logID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.groupByValues) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.filterByValues) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._timestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.logID.isEmpty {
      try visitor.visitSingularStringField(value: self.logID, fieldNumber: 1)
    }
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 2)
    }
    if !self.groupByValues.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.groupByValues, fieldNumber: 3)
    }
    if !self.filterByValues.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.filterByValues, fieldNumber: 4)
    }
    try { if let v = self._timestamp {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Prod_ClickhouseAnalytics_AnalyticsRow, rhs: Prod_ClickhouseAnalytics_AnalyticsRow) -> Bool {
    if lhs.logID != rhs.logID {return false}
    if lhs.values != rhs.values {return false}
    if lhs.groupByValues != rhs.groupByValues {return false}
    if lhs.filterByValues != rhs.filterByValues {return false}
    if lhs._timestamp != rhs._timestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
