// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/auth.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// API key information.
public struct XaiApi_ApiKey: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A redacted API key. The full API key will not be displayed after it has
  /// been created.
  public var redactedApiKey: String = String()

  /// ID of the user who created this API key.
  public var userID: String = String()

  /// Human-readable name for the API key.
  public var name: String = String()

  /// Unix timestamp when the API key was created.
  public var createTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_createTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createTime = newValue}
  }
  /// Returns true if `createTime` has been explicitly set.
  public var hasCreateTime: Bool {self._createTime != nil}
  /// Clears the value of `createTime`. Subsequent reads from it will return its default value.
  public mutating func clearCreateTime() {self._createTime = nil}

  /// Unix timestamp when the API key was last modified.
  public var modifyTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_modifyTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_modifyTime = newValue}
  }
  /// Returns true if `modifyTime` has been explicitly set.
  public var hasModifyTime: Bool {self._modifyTime != nil}
  /// Clears the value of `modifyTime`. Subsequent reads from it will return its default value.
  public mutating func clearModifyTime() {self._modifyTime = nil}

  /// ID of the last user who modified the API key
  public var modifiedBy: String = String()

  /// ID of the team this API key belongs to.
  public var teamID: String = String()

  /// Access Control Lists (ACLs) associated with this key.
  /// These indicate the resources that the API key has access to.
  public var acls: [String] = []

  /// The ID of the API key. This is different from the API key itself.
  public var apiKeyID: String = String()

  /// Whether the API key is currently blocked from making API requests.
  public var apiKeyBlocked: Bool = false

  /// Whether the team is currently blocked from making API requests.
  public var teamBlocked: Bool = false

  /// Whether the API key is currently disabled.
  public var disabled: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _createTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _modifyTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xai_api"

extension XaiApi_ApiKey: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ApiKey"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}redacted_api_key\0\u{4}\u{2}user_id\0\u{1}name\0\u{3}create_time\0\u{3}team_id\0\u{1}acls\0\u{3}api_key_id\0\u{3}modify_time\0\u{3}api_key_blocked\0\u{3}modified_by\0\u{1}disabled\0\u{3}team_blocked\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.redactedApiKey) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._createTime) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.teamID) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.acls) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.apiKeyID) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._modifyTime) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.apiKeyBlocked) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.modifiedBy) }()
      case 12: try { try decoder.decodeSingularBoolField(value: &self.disabled) }()
      case 13: try { try decoder.decodeSingularBoolField(value: &self.teamBlocked) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.redactedApiKey.isEmpty {
      try visitor.visitSingularStringField(value: self.redactedApiKey, fieldNumber: 1)
    }
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 3)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 4)
    }
    try { if let v = self._createTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.teamID.isEmpty {
      try visitor.visitSingularStringField(value: self.teamID, fieldNumber: 6)
    }
    if !self.acls.isEmpty {
      try visitor.visitRepeatedStringField(value: self.acls, fieldNumber: 7)
    }
    if !self.apiKeyID.isEmpty {
      try visitor.visitSingularStringField(value: self.apiKeyID, fieldNumber: 8)
    }
    try { if let v = self._modifyTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    if self.apiKeyBlocked != false {
      try visitor.visitSingularBoolField(value: self.apiKeyBlocked, fieldNumber: 10)
    }
    if !self.modifiedBy.isEmpty {
      try visitor.visitSingularStringField(value: self.modifiedBy, fieldNumber: 11)
    }
    if self.disabled != false {
      try visitor.visitSingularBoolField(value: self.disabled, fieldNumber: 12)
    }
    if self.teamBlocked != false {
      try visitor.visitSingularBoolField(value: self.teamBlocked, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ApiKey, rhs: XaiApi_ApiKey) -> Bool {
    if lhs.redactedApiKey != rhs.redactedApiKey {return false}
    if lhs.userID != rhs.userID {return false}
    if lhs.name != rhs.name {return false}
    if lhs._createTime != rhs._createTime {return false}
    if lhs._modifyTime != rhs._modifyTime {return false}
    if lhs.modifiedBy != rhs.modifiedBy {return false}
    if lhs.teamID != rhs.teamID {return false}
    if lhs.acls != rhs.acls {return false}
    if lhs.apiKeyID != rhs.apiKeyID {return false}
    if lhs.apiKeyBlocked != rhs.apiKeyBlocked {return false}
    if lhs.teamBlocked != rhs.teamBlocked {return false}
    if lhs.disabled != rhs.disabled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
