// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/auth.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - xai_api.Auth

/// Namespace containing generated types for the "xai_api.Auth" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum XaiApi_Auth: Sendable {
    /// Service descriptor for the "xai_api.Auth" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Auth")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "get_api_key_info" metadata.
        public enum get_api_key_info: Sendable {
            /// Request type for "get_api_key_info".
            public typealias Input = SwiftProtobuf.Google_Protobuf_Empty
            /// Response type for "get_api_key_info".
            public typealias Output = XaiApi_ApiKey
            /// Descriptor for "get_api_key_info".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Auth"),
                method: "get_api_key_info"
            )
        }
        /// Descriptors for all methods in the "xai_api.Auth" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            get_api_key_info.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "xai_api.Auth" service.
    public static let xaiApi_Auth = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Auth")
}

// MARK: xai_api.Auth (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Auth {
    /// Generated client protocol for the "xai_api.Auth" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service to check status of an API key.
    public protocol ClientProtocol: Sendable {
        /// Call the "get_api_key_info" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns some information about an API key.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `XaiApi_ApiKey` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func get_api_key_info<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ApiKey>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ApiKey>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "xai_api.Auth" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service to check status of an API key.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "get_api_key_info" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Returns some information about an API key.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
        ///   - serializer: A serializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - deserializer: A deserializer for `XaiApi_ApiKey` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func get_api_key_info<Result>(
            request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
            serializer: some GRPCCore.MessageSerializer<SwiftProtobuf.Google_Protobuf_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ApiKey>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ApiKey>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_Auth.Method.get_api_key_info.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Auth.ClientProtocol {
    /// Call the "get_api_key_info" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Returns some information about an API key.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SwiftProtobuf.Google_Protobuf_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func get_api_key_info<Result>(
        request: GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ApiKey>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.get_api_key_info(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_ApiKey>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Auth.ClientProtocol {
    /// Call the "get_api_key_info" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Returns some information about an API key.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func get_api_key_info<Result>(
        _ message: SwiftProtobuf.Google_Protobuf_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ApiKey>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SwiftProtobuf.Google_Protobuf_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.get_api_key_info(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}