// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/batch.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Holds basic information about a batch process.
public struct XaiApi_Batch: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of the batch. Can be used to retrieve batch results and metadata, etc.
  public var batchID: String {
    get {_storage._batchID}
    set {_uniqueStorage()._batchID = newValue}
  }

  /// The name of the batch.
  public var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// The time when the batch was created.
  public var createTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._createTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._createTime = newValue}
  }
  /// Returns true if `createTime` has been explicitly set.
  public var hasCreateTime: Bool {_storage._createTime != nil}
  /// Clears the value of `createTime`. Subsequent reads from it will return its default value.
  public mutating func clearCreateTime() {_uniqueStorage()._createTime = nil}

  /// The time when the batch expires.
  public var expireTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._expireTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._expireTime = newValue}
  }
  /// Returns true if `expireTime` has been explicitly set.
  public var hasExpireTime: Bool {_storage._expireTime != nil}
  /// Clears the value of `expireTime`. Subsequent reads from it will return its default value.
  public mutating func clearExpireTime() {_uniqueStorage()._expireTime = nil}

  /// ID of the API key that was used to create the batch.
  public var createApiKeyID: String {
    get {_storage._createApiKeyID}
    set {_uniqueStorage()._createApiKeyID = newValue}
  }

  /// Time when the batch was cancelled.
  public var cancelTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._cancelTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._cancelTime = newValue}
  }
  /// Returns true if `cancelTime` has been explicitly set.
  public var hasCancelTime: Bool {_storage._cancelTime != nil}
  /// Clears the value of `cancelTime`. Subsequent reads from it will return its default value.
  public mutating func clearCancelTime() {_uniqueStorage()._cancelTime = nil}

  /// If the batch was cancelled by xAI, an error message explaining why.
  public var cancelByXaiMessage: String {
    get {_storage._cancelByXaiMessage ?? String()}
    set {_uniqueStorage()._cancelByXaiMessage = newValue}
  }
  /// Returns true if `cancelByXaiMessage` has been explicitly set.
  public var hasCancelByXaiMessage: Bool {_storage._cancelByXaiMessage != nil}
  /// Clears the value of `cancelByXaiMessage`. Subsequent reads from it will return its default value.
  public mutating func clearCancelByXaiMessage() {_uniqueStorage()._cancelByXaiMessage = nil}

  /// The state information of the batch. Not always populated.
  public var state: XaiApi_BatchState {
    get {_storage._state ?? XaiApi_BatchState()}
    set {_uniqueStorage()._state = newValue}
  }
  /// Returns true if `state` has been explicitly set.
  public var hasState: Bool {_storage._state != nil}
  /// Clears the value of `state`. Subsequent reads from it will return its default value.
  public mutating func clearState() {_uniqueStorage()._state = nil}

  /// Cost breakdown for processed requests.
  public var costBreakdown: XaiApi_BatchCostBreakdown {
    get {_storage._costBreakdown ?? XaiApi_BatchCostBreakdown()}
    set {_uniqueStorage()._costBreakdown = newValue}
  }
  /// Returns true if `costBreakdown` has been explicitly set.
  public var hasCostBreakdown: Bool {_storage._costBreakdown != nil}
  /// Clears the value of `costBreakdown`. Subsequent reads from it will return its default value.
  public mutating func clearCostBreakdown() {_uniqueStorage()._costBreakdown = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Holds aggregate information about the current state of a batch process.
public struct XaiApi_BatchState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Total number of requests in the batch.
  public var numRequests: Int64 = 0

  /// Total number of pending requests.
  public var numPending: Int64 = 0

  /// Total number of requests that have finished successfully.
  public var numSuccess: Int64 = 0

  /// Total number of requests that finished with an error.
  public var numError: Int64 = 0

  /// Total number of requests that have been cancelled.
  public var numCancelled: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Holds cost information for processed batch requests.
public struct XaiApi_BatchCostBreakdown: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Total cost across all processed requests of all endpoints in USD ticks ($0.0000000001 / $1e-10).
  public var totalCostUsdTicks: Int64 = 0

  /// Cost breakdown by endpoint.
  public var endpointCosts: [XaiApi_EndpointCost] = []

  /// Timestamp when the cost was calculated.
  public var calculationTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_calculationTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_calculationTime = newValue}
  }
  /// Returns true if `calculationTime` has been explicitly set.
  public var hasCalculationTime: Bool {self._calculationTime != nil}
  /// Clears the value of `calculationTime`. Subsequent reads from it will return its default value.
  public mutating func clearCalculationTime() {self._calculationTime = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _calculationTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// Cost breakdown for a specific endpoint.
public struct XaiApi_EndpointCost: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Endpoint for cost aggregation.
  public var endpoint: String = String()

  /// Cost for this endpoint in USD ticks ($0.0000000001 / $1e-10).
  public var costUsdTicks: Int64 = 0

  /// Number of requests processed for this endpoint.
  public var requestCount: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A request that can be added to a batch for processing.
public struct XaiApi_BatchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// An optional user-provided identifier for the input request. If provided, it must be unique within the batch.
  /// Used to identify the corresponding result when the response is returned to the user.
  /// This is because the order of the returned results is not guaranteed to be the same as the order of the requests.
  public var batchRequestID: String {
    get {_batchRequestID ?? String()}
    set {_batchRequestID = newValue}
  }
  /// Returns true if `batchRequestID` has been explicitly set.
  public var hasBatchRequestID: Bool {self._batchRequestID != nil}
  /// Clears the value of `batchRequestID`. Subsequent reads from it will return its default value.
  public mutating func clearBatchRequestID() {self._batchRequestID = nil}

  /// The request to add for processing in the batch.
  public var request: XaiApi_BatchRequest.OneOf_Request? = nil

  /// A completion request to send for processing in the batch.
  public var completionRequest: XaiApi_GetCompletionsRequest {
    get {
      if case .completionRequest(let v)? = request {return v}
      return XaiApi_GetCompletionsRequest()
    }
    set {request = .completionRequest(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The request to add for processing in the batch.
  public enum OneOf_Request: Equatable, Sendable {
    /// A completion request to send for processing in the batch.
    case completionRequest(XaiApi_GetCompletionsRequest)

  }

  public init() {}

  fileprivate var _batchRequestID: String? = nil
}

/// A container for the completion response that is returned in a `BatchResult`.
public struct XaiApi_BatchResultData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The response from the batch request.
  public var response: XaiApi_BatchResultData.OneOf_Response? = nil

  /// A completion response that has finished processing in the batch.
  public var completionResponse: XaiApi_GetChatCompletionResponse {
    get {
      if case .completionResponse(let v)? = response {return v}
      return XaiApi_GetChatCompletionResponse()
    }
    set {response = .completionResponse(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The response from the batch request.
  public enum OneOf_Response: Equatable, Sendable {
    /// A completion response that has finished processing in the batch.
    case completionResponse(XaiApi_GetChatCompletionResponse)

  }

  public init() {}
}

/// The result corresponding to a `BatchRequest`. Returns the result if processing is successful, or error if processing
/// has failed.
public struct XaiApi_BatchResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// User-provided or generated identifier for the batch request. If a user has provided `batch_request_id` in the
  /// `BatchRequest`, the value will match the user-provided value.
  /// The value is unique within the batch.
  public var batchRequestID: String = String()

  /// The result data, or error status if processing has failed.
  public var result: XaiApi_BatchResult.OneOf_Result? = nil

  public var response: XaiApi_BatchResultData {
    get {
      if case .response(let v)? = result {return v}
      return XaiApi_BatchResultData()
    }
    set {result = .response(newValue)}
  }

  public var error: Google_Rpc_Status {
    get {
      if case .error(let v)? = result {return v}
      return Google_Rpc_Status()
    }
    set {result = .error(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The result data, or error status if processing has failed.
  public enum OneOf_Result: Equatable, Sendable {
    case response(XaiApi_BatchResultData)
    case error(Google_Rpc_Status)

  }

  public init() {}
}

/// Metadata about an individual batch request.
public struct XaiApi_BatchRequestMetadata: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// User-provided or generated identifier for the batch request. The value is unique within the batch.
  public var batchRequestID: String = String()

  /// API endpoint to query.
  public var endpoint: String = String()

  /// Model name to query.
  public var model: String = String()

  public var state: XaiApi_BatchRequestMetadata.State = .unknown

  /// Time when the request was recorded.
  public var createTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_createTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createTime = newValue}
  }
  /// Returns true if `createTime` has been explicitly set.
  public var hasCreateTime: Bool {self._createTime != nil}
  /// Clears the value of `createTime`. Subsequent reads from it will return its default value.
  public mutating func clearCreateTime() {self._createTime = nil}

  /// Time when the response was recorded.
  public var finishTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_finishTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_finishTime = newValue}
  }
  /// Returns true if `finishTime` has been explicitly set.
  public var hasFinishTime: Bool {self._finishTime != nil}
  /// Clears the value of `finishTime`. Subsequent reads from it will return its default value.
  public mutating func clearFinishTime() {self._finishTime = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The processing state of this batch request.
  public enum State: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unknown // = 0
    case pending // = 1
    case succeeded // = 2
    case cancelled // = 3
    case failed // = 4
    case UNRECOGNIZED(Int)

    public init() {
      self = .unknown
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unknown
      case 1: self = .pending
      case 2: self = .succeeded
      case 3: self = .cancelled
      case 4: self = .failed
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unknown: return 0
      case .pending: return 1
      case .succeeded: return 2
      case .cancelled: return 3
      case .failed: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [XaiApi_BatchRequestMetadata.State] = [
      .unknown,
      .pending,
      .succeeded,
      .cancelled,
      .failed,
    ]

  }

  public init() {}

  fileprivate var _createTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _finishTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// Request to create a new batch.
public struct XaiApi_CreateBatchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the batch to be created.
  public var name: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request to add `BatchRequest`s to an existing batch for processing.
public struct XaiApi_AddBatchRequestsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of the batch to add the requests to.
  public var batchID: String = String()

  /// The requests to add to the batch.
  public var batchRequests: [XaiApi_BatchRequest] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request to get the information of a batch.
public struct XaiApi_GetBatchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of the batch.
  public var batchID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request to list all batches in the team.
public struct XaiApi_ListBatchesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Number of batches to return on a page. Defaults to 100.
  public var limit: Int32 = 0

  /// Optional pagination token to retrieve a specific page. Provided by `pagination_token` in `ListBatchesResponse`.
  public var paginationToken: String {
    get {_paginationToken ?? String()}
    set {_paginationToken = newValue}
  }
  /// Returns true if `paginationToken` has been explicitly set.
  public var hasPaginationToken: Bool {self._paginationToken != nil}
  /// Clears the value of `paginationToken`. Subsequent reads from it will return its default value.
  public mutating func clearPaginationToken() {self._paginationToken = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _paginationToken: String? = nil
}

/// Response containing all the batches on a page.
public struct XaiApi_ListBatchesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The information about the batches.
  public var batches: [XaiApi_Batch] = []

  /// The pagination token to retrieve batches from the next page. Will be empty if this is the last page.
  public var paginationToken: String {
    get {_paginationToken ?? String()}
    set {_paginationToken = newValue}
  }
  /// Returns true if `paginationToken` has been explicitly set.
  public var hasPaginationToken: Bool {self._paginationToken != nil}
  /// Clears the value of `paginationToken`. Subsequent reads from it will return its default value.
  public mutating func clearPaginationToken() {self._paginationToken = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _paginationToken: String? = nil
}

/// Request to cancel processing of all the batch requests in a batch.
public struct XaiApi_CancelBatchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of the batch that we are cancelling the requests.
  public var batchID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request for the request metadata within a batch.
public struct XaiApi_ListBatchRequestMetadataRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ID of the batch whose batch requests' metadata shall be listed.
  public var batchID: String = String()

  /// Number of batch request metadata to return on a page. Defaults to 100.
  public var limit: Int32 = 0

  /// Optional pagination token to retrieve a specific page. Provided by `pagination_token` in `ListBatchRequestMetadataResponse`.
  public var paginationToken: String {
    get {_paginationToken ?? String()}
    set {_paginationToken = newValue}
  }
  /// Returns true if `paginationToken` has been explicitly set.
  public var hasPaginationToken: Bool {self._paginationToken != nil}
  /// Clears the value of `paginationToken`. Subsequent reads from it will return its default value.
  public mutating func clearPaginationToken() {self._paginationToken = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _paginationToken: String? = nil
}

/// Response with the metadata of batch requests within a batch.
public struct XaiApi_ListBatchRequestMetadataResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The batch requests' metadata for the given batch.
  public var batchRequestMetadata: [XaiApi_BatchRequestMetadata] = []

  /// The pagination token to retrieve results from the next page. Will be empty if this is the last page.
  public var paginationToken: String {
    get {_paginationToken ?? String()}
    set {_paginationToken = newValue}
  }
  /// Returns true if `paginationToken` has been explicitly set.
  public var hasPaginationToken: Bool {self._paginationToken != nil}
  /// Clears the value of `paginationToken`. Subsequent reads from it will return its default value.
  public mutating func clearPaginationToken() {self._paginationToken = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _paginationToken: String? = nil
}

/// Request to list a batch's processing results.
public struct XaiApi_ListBatchResultsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of the batch we are retrieving the results from.
  public var batchID: String = String()

  /// Number of batch request results to return on a page. Defaults to 100.
  public var limit: Int32 = 0

  /// Optional pagination token to retrieve a specific page. Provided by `pagination_token` in `ListBatchResultsResponse`.
  public var paginationToken: String {
    get {_paginationToken ?? String()}
    set {_paginationToken = newValue}
  }
  /// Returns true if `paginationToken` has been explicitly set.
  public var hasPaginationToken: Bool {self._paginationToken != nil}
  /// Clears the value of `paginationToken`. Subsequent reads from it will return its default value.
  public mutating func clearPaginationToken() {self._paginationToken = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _paginationToken: String? = nil
}

/// Response with the batch's processing results.
public struct XaiApi_ListBatchResultsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The results that has been processed.
  public var results: [XaiApi_BatchResult] = []

  /// The pagination token to retrieve results from the next page. Will be empty if this is the last page.
  public var paginationToken: String {
    get {_paginationToken ?? String()}
    set {_paginationToken = newValue}
  }
  /// Returns true if `paginationToken` has been explicitly set.
  public var hasPaginationToken: Bool {self._paginationToken != nil}
  /// Clears the value of `paginationToken`. Subsequent reads from it will return its default value.
  public mutating func clearPaginationToken() {self._paginationToken = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _paginationToken: String? = nil
}

public struct XaiApi_GetBatchRequestResultRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of the batch we are retrieving the request from.
  public var batchID: String = String()

  /// The ID of the request we are retrieving.
  public var batchRequestID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct XaiApi_GetBatchRequestResultResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The request that was processed.
  public var request: XaiApi_BatchRequest {
    get {_request ?? XaiApi_BatchRequest()}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  public var hasRequest: Bool {self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  public mutating func clearRequest() {self._request = nil}

  /// The response that was returned.
  public var result: XaiApi_BatchResult {
    get {_result ?? XaiApi_BatchResult()}
    set {_result = newValue}
  }
  /// Returns true if `result` has been explicitly set.
  public var hasResult: Bool {self._result != nil}
  /// Clears the value of `result`. Subsequent reads from it will return its default value.
  public mutating func clearResult() {self._result = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _request: XaiApi_BatchRequest? = nil
  fileprivate var _result: XaiApi_BatchResult? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xai_api"

extension XaiApi_Batch: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Batch"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0\u{1}name\0\u{3}create_time\0\u{3}expire_time\0\u{3}create_api_key_id\0\u{3}cancel_time\0\u{3}cancel_by_xai_message\0\u{1}state\0\u{3}cost_breakdown\0")

  fileprivate class _StorageClass {
    var _batchID: String = String()
    var _name: String = String()
    var _createTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _expireTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _createApiKeyID: String = String()
    var _cancelTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _cancelByXaiMessage: String? = nil
    var _state: XaiApi_BatchState? = nil
    var _costBreakdown: XaiApi_BatchCostBreakdown? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _batchID = source._batchID
      _name = source._name
      _createTime = source._createTime
      _expireTime = source._expireTime
      _createApiKeyID = source._createApiKeyID
      _cancelTime = source._cancelTime
      _cancelByXaiMessage = source._cancelByXaiMessage
      _state = source._state
      _costBreakdown = source._costBreakdown
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._batchID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._createTime) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._expireTime) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._createApiKeyID) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._cancelTime) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._cancelByXaiMessage) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._state) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._costBreakdown) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._batchID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._batchID, fieldNumber: 1)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      try { if let v = _storage._createTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._expireTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      if !_storage._createApiKeyID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._createApiKeyID, fieldNumber: 5)
      }
      try { if let v = _storage._cancelTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._cancelByXaiMessage {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._state {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._costBreakdown {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_Batch, rhs: XaiApi_Batch) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._batchID != rhs_storage._batchID {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._createTime != rhs_storage._createTime {return false}
        if _storage._expireTime != rhs_storage._expireTime {return false}
        if _storage._createApiKeyID != rhs_storage._createApiKeyID {return false}
        if _storage._cancelTime != rhs_storage._cancelTime {return false}
        if _storage._cancelByXaiMessage != rhs_storage._cancelByXaiMessage {return false}
        if _storage._state != rhs_storage._state {return false}
        if _storage._costBreakdown != rhs_storage._costBreakdown {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_BatchState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BatchState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}num_requests\0\u{3}num_pending\0\u{3}num_success\0\u{3}num_error\0\u{3}num_cancelled\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.numRequests) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.numPending) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.numSuccess) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.numError) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.numCancelled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.numRequests != 0 {
      try visitor.visitSingularInt64Field(value: self.numRequests, fieldNumber: 1)
    }
    if self.numPending != 0 {
      try visitor.visitSingularInt64Field(value: self.numPending, fieldNumber: 2)
    }
    if self.numSuccess != 0 {
      try visitor.visitSingularInt64Field(value: self.numSuccess, fieldNumber: 3)
    }
    if self.numError != 0 {
      try visitor.visitSingularInt64Field(value: self.numError, fieldNumber: 4)
    }
    if self.numCancelled != 0 {
      try visitor.visitSingularInt64Field(value: self.numCancelled, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_BatchState, rhs: XaiApi_BatchState) -> Bool {
    if lhs.numRequests != rhs.numRequests {return false}
    if lhs.numPending != rhs.numPending {return false}
    if lhs.numSuccess != rhs.numSuccess {return false}
    if lhs.numError != rhs.numError {return false}
    if lhs.numCancelled != rhs.numCancelled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_BatchCostBreakdown: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BatchCostBreakdown"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}total_cost_usd_ticks\0\u{3}endpoint_costs\0\u{3}calculation_time\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.totalCostUsdTicks) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.endpointCosts) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._calculationTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.totalCostUsdTicks != 0 {
      try visitor.visitSingularInt64Field(value: self.totalCostUsdTicks, fieldNumber: 1)
    }
    if !self.endpointCosts.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.endpointCosts, fieldNumber: 2)
    }
    try { if let v = self._calculationTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_BatchCostBreakdown, rhs: XaiApi_BatchCostBreakdown) -> Bool {
    if lhs.totalCostUsdTicks != rhs.totalCostUsdTicks {return false}
    if lhs.endpointCosts != rhs.endpointCosts {return false}
    if lhs._calculationTime != rhs._calculationTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_EndpointCost: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EndpointCost"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}endpoint\0\u{3}cost_usd_ticks\0\u{3}request_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.endpoint) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.costUsdTicks) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.requestCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.endpoint.isEmpty {
      try visitor.visitSingularStringField(value: self.endpoint, fieldNumber: 1)
    }
    if self.costUsdTicks != 0 {
      try visitor.visitSingularInt64Field(value: self.costUsdTicks, fieldNumber: 2)
    }
    if self.requestCount != 0 {
      try visitor.visitSingularInt64Field(value: self.requestCount, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_EndpointCost, rhs: XaiApi_EndpointCost) -> Bool {
    if lhs.endpoint != rhs.endpoint {return false}
    if lhs.costUsdTicks != rhs.costUsdTicks {return false}
    if lhs.requestCount != rhs.requestCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_BatchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BatchRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_request_id\0\u{3}completion_request\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._batchRequestID) }()
      case 2: try {
        var v: XaiApi_GetCompletionsRequest?
        var hadOneofValue = false
        if let current = self.request {
          hadOneofValue = true
          if case .completionRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.request = .completionRequest(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._batchRequestID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if case .completionRequest(let v)? = self.request {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_BatchRequest, rhs: XaiApi_BatchRequest) -> Bool {
    if lhs._batchRequestID != rhs._batchRequestID {return false}
    if lhs.request != rhs.request {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_BatchResultData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BatchResultData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}completion_response\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try {
        var v: XaiApi_GetChatCompletionResponse?
        var hadOneofValue = false
        if let current = self.response {
          hadOneofValue = true
          if case .completionResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.response = .completionResponse(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if case .completionResponse(let v)? = self.response {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_BatchResultData, rhs: XaiApi_BatchResultData) -> Bool {
    if lhs.response != rhs.response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_BatchResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BatchResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_request_id\0\u{2}\u{2}error\0\u{1}response\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchRequestID) }()
      case 3: try {
        var v: Google_Rpc_Status?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .error(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .error(v)
        }
      }()
      case 4: try {
        var v: XaiApi_BatchResultData?
        var hadOneofValue = false
        if let current = self.result {
          hadOneofValue = true
          if case .response(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.result = .response(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.batchRequestID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchRequestID, fieldNumber: 1)
    }
    switch self.result {
    case .error?: try {
      guard case .error(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .response?: try {
      guard case .response(let v)? = self.result else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_BatchResult, rhs: XaiApi_BatchResult) -> Bool {
    if lhs.batchRequestID != rhs.batchRequestID {return false}
    if lhs.result != rhs.result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_BatchRequestMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BatchRequestMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_request_id\0\u{1}endpoint\0\u{1}model\0\u{1}state\0\u{3}create_time\0\u{3}finish_time\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchRequestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.endpoint) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.state) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._createTime) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._finishTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.batchRequestID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchRequestID, fieldNumber: 1)
    }
    if !self.endpoint.isEmpty {
      try visitor.visitSingularStringField(value: self.endpoint, fieldNumber: 2)
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 3)
    }
    if self.state != .unknown {
      try visitor.visitSingularEnumField(value: self.state, fieldNumber: 4)
    }
    try { if let v = self._createTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._finishTime {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_BatchRequestMetadata, rhs: XaiApi_BatchRequestMetadata) -> Bool {
    if lhs.batchRequestID != rhs.batchRequestID {return false}
    if lhs.endpoint != rhs.endpoint {return false}
    if lhs.model != rhs.model {return false}
    if lhs.state != rhs.state {return false}
    if lhs._createTime != rhs._createTime {return false}
    if lhs._finishTime != rhs._finishTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_BatchRequestMetadata.State: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STATE_UNKNOWN\0\u{1}STATE_PENDING\0\u{1}STATE_SUCCEEDED\0\u{1}STATE_CANCELLED\0\u{1}STATE_FAILED\0")
}

extension XaiApi_CreateBatchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CreateBatchRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_CreateBatchRequest, rhs: XaiApi_CreateBatchRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_AddBatchRequestsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AddBatchRequestsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0\u{3}batch_requests\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchID) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.batchRequests) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.batchID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchID, fieldNumber: 1)
    }
    if !self.batchRequests.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.batchRequests, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_AddBatchRequestsRequest, rhs: XaiApi_AddBatchRequestsRequest) -> Bool {
    if lhs.batchID != rhs.batchID {return false}
    if lhs.batchRequests != rhs.batchRequests {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_GetBatchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetBatchRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.batchID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GetBatchRequest, rhs: XaiApi_GetBatchRequest) -> Bool {
    if lhs.batchID != rhs.batchID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListBatchesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListBatchesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}limit\0\u{3}pagination_token\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.limit) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._paginationToken) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.limit != 0 {
      try visitor.visitSingularInt32Field(value: self.limit, fieldNumber: 1)
    }
    try { if let v = self._paginationToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListBatchesRequest, rhs: XaiApi_ListBatchesRequest) -> Bool {
    if lhs.limit != rhs.limit {return false}
    if lhs._paginationToken != rhs._paginationToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListBatchesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListBatchesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}batches\0\u{3}pagination_token\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.batches) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._paginationToken) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.batches.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.batches, fieldNumber: 1)
    }
    try { if let v = self._paginationToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListBatchesResponse, rhs: XaiApi_ListBatchesResponse) -> Bool {
    if lhs.batches != rhs.batches {return false}
    if lhs._paginationToken != rhs._paginationToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_CancelBatchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CancelBatchRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.batchID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_CancelBatchRequest, rhs: XaiApi_CancelBatchRequest) -> Bool {
    if lhs.batchID != rhs.batchID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListBatchRequestMetadataRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListBatchRequestMetadataRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0\u{1}limit\0\u{3}pagination_token\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.limit) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._paginationToken) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.batchID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchID, fieldNumber: 1)
    }
    if self.limit != 0 {
      try visitor.visitSingularInt32Field(value: self.limit, fieldNumber: 2)
    }
    try { if let v = self._paginationToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListBatchRequestMetadataRequest, rhs: XaiApi_ListBatchRequestMetadataRequest) -> Bool {
    if lhs.batchID != rhs.batchID {return false}
    if lhs.limit != rhs.limit {return false}
    if lhs._paginationToken != rhs._paginationToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListBatchRequestMetadataResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListBatchRequestMetadataResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_request_metadata\0\u{3}pagination_token\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.batchRequestMetadata) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._paginationToken) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.batchRequestMetadata.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.batchRequestMetadata, fieldNumber: 1)
    }
    try { if let v = self._paginationToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListBatchRequestMetadataResponse, rhs: XaiApi_ListBatchRequestMetadataResponse) -> Bool {
    if lhs.batchRequestMetadata != rhs.batchRequestMetadata {return false}
    if lhs._paginationToken != rhs._paginationToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListBatchResultsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListBatchResultsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0\u{1}limit\0\u{3}pagination_token\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.limit) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._paginationToken) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.batchID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchID, fieldNumber: 1)
    }
    if self.limit != 0 {
      try visitor.visitSingularInt32Field(value: self.limit, fieldNumber: 2)
    }
    try { if let v = self._paginationToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListBatchResultsRequest, rhs: XaiApi_ListBatchResultsRequest) -> Bool {
    if lhs.batchID != rhs.batchID {return false}
    if lhs.limit != rhs.limit {return false}
    if lhs._paginationToken != rhs._paginationToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListBatchResultsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListBatchResultsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}results\0\u{3}pagination_token\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.results) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._paginationToken) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.results.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.results, fieldNumber: 1)
    }
    try { if let v = self._paginationToken {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListBatchResultsResponse, rhs: XaiApi_ListBatchResultsResponse) -> Bool {
    if lhs.results != rhs.results {return false}
    if lhs._paginationToken != rhs._paginationToken {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_GetBatchRequestResultRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetBatchRequestResultRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}batch_id\0\u{3}batch_request_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.batchID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.batchRequestID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.batchID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchID, fieldNumber: 1)
    }
    if !self.batchRequestID.isEmpty {
      try visitor.visitSingularStringField(value: self.batchRequestID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GetBatchRequestResultRequest, rhs: XaiApi_GetBatchRequestResultRequest) -> Bool {
    if lhs.batchID != rhs.batchID {return false}
    if lhs.batchRequestID != rhs.batchRequestID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_GetBatchRequestResultResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetBatchRequestResultResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}request\0\u{1}result\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._request) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._result) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._request {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._result {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GetBatchRequestResultResponse, rhs: XaiApi_GetBatchRequestResultResponse) -> Bool {
    if lhs._request != rhs._request {return false}
    if lhs._result != rhs._result {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
