// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/batch.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf
import SwiftProtobuf

// MARK: - xai_api.BatchMgmt

/// Namespace containing generated types for the "xai_api.BatchMgmt" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum XaiApi_BatchMgmt: Sendable {
    /// Service descriptor for the "xai_api.BatchMgmt" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "CreateBatch" metadata.
        public enum CreateBatch: Sendable {
            /// Request type for "CreateBatch".
            public typealias Input = XaiApi_CreateBatchRequest
            /// Response type for "CreateBatch".
            public typealias Output = XaiApi_Batch
            /// Descriptor for "CreateBatch".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt"),
                method: "CreateBatch",
                type: .unary
            )
        }
        /// Namespace for "GetBatch" metadata.
        public enum GetBatch: Sendable {
            /// Request type for "GetBatch".
            public typealias Input = XaiApi_GetBatchRequest
            /// Response type for "GetBatch".
            public typealias Output = XaiApi_Batch
            /// Descriptor for "GetBatch".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt"),
                method: "GetBatch",
                type: .unary
            )
        }
        /// Namespace for "ListBatches" metadata.
        public enum ListBatches: Sendable {
            /// Request type for "ListBatches".
            public typealias Input = XaiApi_ListBatchesRequest
            /// Response type for "ListBatches".
            public typealias Output = XaiApi_ListBatchesResponse
            /// Descriptor for "ListBatches".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt"),
                method: "ListBatches",
                type: .unary
            )
        }
        /// Namespace for "CancelBatch" metadata.
        public enum CancelBatch: Sendable {
            /// Request type for "CancelBatch".
            public typealias Input = XaiApi_CancelBatchRequest
            /// Response type for "CancelBatch".
            public typealias Output = XaiApi_Batch
            /// Descriptor for "CancelBatch".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt"),
                method: "CancelBatch",
                type: .unary
            )
        }
        /// Namespace for "AddBatchRequests" metadata.
        public enum AddBatchRequests: Sendable {
            /// Request type for "AddBatchRequests".
            public typealias Input = XaiApi_AddBatchRequestsRequest
            /// Response type for "AddBatchRequests".
            public typealias Output = SwiftProtobuf.Google_Protobuf_Empty
            /// Descriptor for "AddBatchRequests".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt"),
                method: "AddBatchRequests",
                type: .unary
            )
        }
        /// Namespace for "ListBatchRequestMetadata" metadata.
        public enum ListBatchRequestMetadata: Sendable {
            /// Request type for "ListBatchRequestMetadata".
            public typealias Input = XaiApi_ListBatchRequestMetadataRequest
            /// Response type for "ListBatchRequestMetadata".
            public typealias Output = XaiApi_ListBatchRequestMetadataResponse
            /// Descriptor for "ListBatchRequestMetadata".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt"),
                method: "ListBatchRequestMetadata",
                type: .unary
            )
        }
        /// Namespace for "ListBatchResults" metadata.
        public enum ListBatchResults: Sendable {
            /// Request type for "ListBatchResults".
            public typealias Input = XaiApi_ListBatchResultsRequest
            /// Response type for "ListBatchResults".
            public typealias Output = XaiApi_ListBatchResultsResponse
            /// Descriptor for "ListBatchResults".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt"),
                method: "ListBatchResults",
                type: .unary
            )
        }
        /// Namespace for "GetBatchRequestResult" metadata.
        public enum GetBatchRequestResult: Sendable {
            /// Request type for "GetBatchRequestResult".
            public typealias Input = XaiApi_GetBatchRequestResultRequest
            /// Response type for "GetBatchRequestResult".
            public typealias Output = XaiApi_GetBatchRequestResultResponse
            /// Descriptor for "GetBatchRequestResult".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt"),
                method: "GetBatchRequestResult",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "xai_api.BatchMgmt" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            CreateBatch.descriptor,
            GetBatch.descriptor,
            ListBatches.descriptor,
            CancelBatch.descriptor,
            AddBatchRequests.descriptor,
            ListBatchRequestMetadata.descriptor,
            ListBatchResults.descriptor,
            GetBatchRequestResult.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "xai_api.BatchMgmt" service.
    public static let xaiApi_BatchMgmt = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.BatchMgmt")
}

// MARK: xai_api.BatchMgmt (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_BatchMgmt {
    /// Generated client protocol for the "xai_api.BatchMgmt" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for processing batch requests asynchronously at lower priority than chat service.
    public protocol ClientProtocol: Sendable {
        /// Call the "CreateBatch" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates a new batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_CreateBatchRequest` message.
        ///   - serializer: A serializer for `XaiApi_CreateBatchRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_Batch` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createBatch<Result>(
            request: GRPCCore.ClientRequest<XaiApi_CreateBatchRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_CreateBatchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_Batch>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetBatch" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Retrieves an individual batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GetBatchRequest` message.
        ///   - serializer: A serializer for `XaiApi_GetBatchRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_Batch` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getBatch<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GetBatchRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GetBatchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_Batch>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListBatches" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Retrieves a list of all batches owned by the team.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_ListBatchesRequest` message.
        ///   - serializer: A serializer for `XaiApi_ListBatchesRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_ListBatchesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listBatches<Result>(
            request: GRPCCore.ClientRequest<XaiApi_ListBatchesRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_ListBatchesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ListBatchesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CancelBatch" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Stops processing of all outstanding requests in the batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_CancelBatchRequest` message.
        ///   - serializer: A serializer for `XaiApi_CancelBatchRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_Batch` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func cancelBatch<Result>(
            request: GRPCCore.ClientRequest<XaiApi_CancelBatchRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_CancelBatchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_Batch>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "AddBatchRequests" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Adds requests to a batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_AddBatchRequestsRequest` message.
        ///   - serializer: A serializer for `XaiApi_AddBatchRequestsRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func addBatchRequests<Result>(
            request: GRPCCore.ClientRequest<XaiApi_AddBatchRequestsRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_AddBatchRequestsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListBatchRequestMetadata" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists metadata about individual requests in a batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_ListBatchRequestMetadataRequest` message.
        ///   - serializer: A serializer for `XaiApi_ListBatchRequestMetadataRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_ListBatchRequestMetadataResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listBatchRequestMetadata<Result>(
            request: GRPCCore.ClientRequest<XaiApi_ListBatchRequestMetadataRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_ListBatchRequestMetadataRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ListBatchRequestMetadataResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchRequestMetadataResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListBatchResults" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists processing results of a batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_ListBatchResultsRequest` message.
        ///   - serializer: A serializer for `XaiApi_ListBatchResultsRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_ListBatchResultsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listBatchResults<Result>(
            request: GRPCCore.ClientRequest<XaiApi_ListBatchResultsRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_ListBatchResultsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ListBatchResultsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchResultsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetBatchRequestResult" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Retrieves an individual request in a batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GetBatchRequestResultRequest` message.
        ///   - serializer: A serializer for `XaiApi_GetBatchRequestResultRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_GetBatchRequestResultResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getBatchRequestResult<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GetBatchRequestResultRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GetBatchRequestResultRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_GetBatchRequestResultResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_GetBatchRequestResultResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "xai_api.BatchMgmt" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for processing batch requests asynchronously at lower priority than chat service.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "CreateBatch" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Creates a new batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_CreateBatchRequest` message.
        ///   - serializer: A serializer for `XaiApi_CreateBatchRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_Batch` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createBatch<Result>(
            request: GRPCCore.ClientRequest<XaiApi_CreateBatchRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_CreateBatchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_Batch>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_BatchMgmt.Method.CreateBatch.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetBatch" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Retrieves an individual batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GetBatchRequest` message.
        ///   - serializer: A serializer for `XaiApi_GetBatchRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_Batch` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getBatch<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GetBatchRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GetBatchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_Batch>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_BatchMgmt.Method.GetBatch.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListBatches" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Retrieves a list of all batches owned by the team.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_ListBatchesRequest` message.
        ///   - serializer: A serializer for `XaiApi_ListBatchesRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_ListBatchesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listBatches<Result>(
            request: GRPCCore.ClientRequest<XaiApi_ListBatchesRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_ListBatchesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ListBatchesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_BatchMgmt.Method.ListBatches.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CancelBatch" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Stops processing of all outstanding requests in the batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_CancelBatchRequest` message.
        ///   - serializer: A serializer for `XaiApi_CancelBatchRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_Batch` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func cancelBatch<Result>(
            request: GRPCCore.ClientRequest<XaiApi_CancelBatchRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_CancelBatchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_Batch>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_BatchMgmt.Method.CancelBatch.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "AddBatchRequests" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Adds requests to a batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_AddBatchRequestsRequest` message.
        ///   - serializer: A serializer for `XaiApi_AddBatchRequestsRequest` messages.
        ///   - deserializer: A deserializer for `SwiftProtobuf.Google_Protobuf_Empty` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func addBatchRequests<Result>(
            request: GRPCCore.ClientRequest<XaiApi_AddBatchRequestsRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_AddBatchRequestsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SwiftProtobuf.Google_Protobuf_Empty>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_BatchMgmt.Method.AddBatchRequests.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListBatchRequestMetadata" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists metadata about individual requests in a batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_ListBatchRequestMetadataRequest` message.
        ///   - serializer: A serializer for `XaiApi_ListBatchRequestMetadataRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_ListBatchRequestMetadataResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listBatchRequestMetadata<Result>(
            request: GRPCCore.ClientRequest<XaiApi_ListBatchRequestMetadataRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_ListBatchRequestMetadataRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ListBatchRequestMetadataResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchRequestMetadataResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_BatchMgmt.Method.ListBatchRequestMetadata.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListBatchResults" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Lists processing results of a batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_ListBatchResultsRequest` message.
        ///   - serializer: A serializer for `XaiApi_ListBatchResultsRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_ListBatchResultsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listBatchResults<Result>(
            request: GRPCCore.ClientRequest<XaiApi_ListBatchResultsRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_ListBatchResultsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ListBatchResultsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchResultsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_BatchMgmt.Method.ListBatchResults.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetBatchRequestResult" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Retrieves an individual request in a batch.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GetBatchRequestResultRequest` message.
        ///   - serializer: A serializer for `XaiApi_GetBatchRequestResultRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_GetBatchRequestResultResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getBatchRequestResult<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GetBatchRequestResultRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GetBatchRequestResultRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_GetBatchRequestResultResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_GetBatchRequestResultResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_BatchMgmt.Method.GetBatchRequestResult.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_BatchMgmt.ClientProtocol {
    /// Call the "CreateBatch" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates a new batch.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_CreateBatchRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createBatch<Result>(
        request: GRPCCore.ClientRequest<XaiApi_CreateBatchRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createBatch(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_CreateBatchRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_Batch>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetBatch" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Retrieves an individual batch.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_GetBatchRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBatch<Result>(
        request: GRPCCore.ClientRequest<XaiApi_GetBatchRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getBatch(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_GetBatchRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_Batch>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListBatches" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Retrieves a list of all batches owned by the team.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_ListBatchesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listBatches<Result>(
        request: GRPCCore.ClientRequest<XaiApi_ListBatchesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listBatches(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_ListBatchesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_ListBatchesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CancelBatch" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Stops processing of all outstanding requests in the batch.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_CancelBatchRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func cancelBatch<Result>(
        request: GRPCCore.ClientRequest<XaiApi_CancelBatchRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.cancelBatch(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_CancelBatchRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_Batch>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AddBatchRequests" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Adds requests to a batch.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_AddBatchRequestsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func addBatchRequests<Result>(
        request: GRPCCore.ClientRequest<XaiApi_AddBatchRequestsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.addBatchRequests(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_AddBatchRequestsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SwiftProtobuf.Google_Protobuf_Empty>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListBatchRequestMetadata" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists metadata about individual requests in a batch.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_ListBatchRequestMetadataRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listBatchRequestMetadata<Result>(
        request: GRPCCore.ClientRequest<XaiApi_ListBatchRequestMetadataRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchRequestMetadataResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listBatchRequestMetadata(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_ListBatchRequestMetadataRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_ListBatchRequestMetadataResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListBatchResults" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists processing results of a batch.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_ListBatchResultsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listBatchResults<Result>(
        request: GRPCCore.ClientRequest<XaiApi_ListBatchResultsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchResultsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listBatchResults(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_ListBatchResultsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_ListBatchResultsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetBatchRequestResult" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Retrieves an individual request in a batch.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_GetBatchRequestResultRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBatchRequestResult<Result>(
        request: GRPCCore.ClientRequest<XaiApi_GetBatchRequestResultRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_GetBatchRequestResultResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getBatchRequestResult(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_GetBatchRequestResultRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_GetBatchRequestResultResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_BatchMgmt.ClientProtocol {
    /// Call the "CreateBatch" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Creates a new batch.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createBatch<Result>(
        _ message: XaiApi_CreateBatchRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_CreateBatchRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createBatch(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetBatch" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Retrieves an individual batch.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBatch<Result>(
        _ message: XaiApi_GetBatchRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_GetBatchRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getBatch(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListBatches" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Retrieves a list of all batches owned by the team.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listBatches<Result>(
        _ message: XaiApi_ListBatchesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_ListBatchesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listBatches(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CancelBatch" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Stops processing of all outstanding requests in the batch.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func cancelBatch<Result>(
        _ message: XaiApi_CancelBatchRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_Batch>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_CancelBatchRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.cancelBatch(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AddBatchRequests" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Adds requests to a batch.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func addBatchRequests<Result>(
        _ message: XaiApi_AddBatchRequestsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SwiftProtobuf.Google_Protobuf_Empty>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_AddBatchRequestsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.addBatchRequests(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListBatchRequestMetadata" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists metadata about individual requests in a batch.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listBatchRequestMetadata<Result>(
        _ message: XaiApi_ListBatchRequestMetadataRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchRequestMetadataResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_ListBatchRequestMetadataRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listBatchRequestMetadata(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListBatchResults" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Lists processing results of a batch.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listBatchResults<Result>(
        _ message: XaiApi_ListBatchResultsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ListBatchResultsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_ListBatchResultsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listBatchResults(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetBatchRequestResult" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Retrieves an individual request in a batch.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBatchRequestResult<Result>(
        _ message: XaiApi_GetBatchRequestResultRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_GetBatchRequestResultResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_GetBatchRequestResultRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getBatchRequestResult(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}