// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/embed.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - xai_api.Embedder

/// Namespace containing generated types for the "xai_api.Embedder" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum XaiApi_Embedder: Sendable {
    /// Service descriptor for the "xai_api.Embedder" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Embedder")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "Embed" metadata.
        public enum Embed: Sendable {
            /// Request type for "Embed".
            public typealias Input = XaiApi_EmbedRequest
            /// Response type for "Embed".
            public typealias Output = XaiApi_EmbedResponse
            /// Descriptor for "Embed".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Embedder"),
                method: "Embed"
            )
        }
        /// Descriptors for all methods in the "xai_api.Embedder" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Embed.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "xai_api.Embedder" service.
    public static let xaiApi_Embedder = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Embedder")
}

// MARK: xai_api.Embedder (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Embedder {
    /// Generated client protocol for the "xai_api.Embedder" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for interaction with available embedding models.
    public protocol ClientProtocol: Sendable {
        /// Call the "Embed" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Produces one embedding for each input object. The size of the produced
        /// > feature vectors depends on the chosen model.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_EmbedRequest` message.
        ///   - serializer: A serializer for `XaiApi_EmbedRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_EmbedResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func embed<Result>(
            request: GRPCCore.ClientRequest<XaiApi_EmbedRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_EmbedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_EmbedResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_EmbedResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "xai_api.Embedder" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for interaction with available embedding models.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Embed" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Produces one embedding for each input object. The size of the produced
        /// > feature vectors depends on the chosen model.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_EmbedRequest` message.
        ///   - serializer: A serializer for `XaiApi_EmbedRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_EmbedResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func embed<Result>(
            request: GRPCCore.ClientRequest<XaiApi_EmbedRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_EmbedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_EmbedResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_EmbedResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_Embedder.Method.Embed.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Embedder.ClientProtocol {
    /// Call the "Embed" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Produces one embedding for each input object. The size of the produced
    /// > feature vectors depends on the chosen model.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_EmbedRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embed<Result>(
        request: GRPCCore.ClientRequest<XaiApi_EmbedRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_EmbedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.embed(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_EmbedRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_EmbedResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Embedder.ClientProtocol {
    /// Call the "Embed" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Produces one embedding for each input object. The size of the produced
    /// > feature vectors depends on the chosen model.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func embed<Result>(
        _ message: XaiApi_EmbedRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_EmbedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_EmbedRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.embed(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}