// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/image.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - xai_api.Image

/// Namespace containing generated types for the "xai_api.Image" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum XaiApi_Image: Sendable {
    /// Service descriptor for the "xai_api.Image" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Image")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GenerateImage" metadata.
        public enum GenerateImage: Sendable {
            /// Request type for "GenerateImage".
            public typealias Input = XaiApi_GenerateImageRequest
            /// Response type for "GenerateImage".
            public typealias Output = XaiApi_ImageResponse
            /// Descriptor for "GenerateImage".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Image"),
                method: "GenerateImage"
            )
        }
        /// Descriptors for all methods in the "xai_api.Image" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GenerateImage.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "xai_api.Image" service.
    public static let xaiApi_Image = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Image")
}

// MARK: xai_api.Image (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Image {
    /// Generated client protocol for the "xai_api.Image" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for interaction with image generation models.
    public protocol ClientProtocol: Sendable {
        /// Call the "GenerateImage" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create an image based on a text prompt and optionally another image.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GenerateImageRequest` message.
        ///   - serializer: A serializer for `XaiApi_GenerateImageRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_ImageResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func generateImage<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GenerateImageRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GenerateImageRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ImageResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ImageResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "xai_api.Image" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for interaction with image generation models.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GenerateImage" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create an image based on a text prompt and optionally another image.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GenerateImageRequest` message.
        ///   - serializer: A serializer for `XaiApi_GenerateImageRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_ImageResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func generateImage<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GenerateImageRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GenerateImageRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_ImageResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ImageResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_Image.Method.GenerateImage.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Image.ClientProtocol {
    /// Call the "GenerateImage" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create an image based on a text prompt and optionally another image.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_GenerateImageRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateImage<Result>(
        request: GRPCCore.ClientRequest<XaiApi_GenerateImageRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ImageResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.generateImage(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_GenerateImageRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_ImageResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Image.ClientProtocol {
    /// Call the "GenerateImage" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create an image based on a text prompt and optionally another image.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateImage<Result>(
        _ message: XaiApi_GenerateImageRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_ImageResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_GenerateImageRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.generateImage(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}