// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/image.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Indicates the level of preprocessing to apply to images that will be fed to
/// the model.
public enum XaiApi_ImageDetail: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Detail level is invalid.
  case detailInvalid // = 0

  /// The system will decide the image resolution to use.
  case detailAuto // = 1

  /// The model will process a low-resolution version of the image. This is
  /// faster and cheaper (i.e. consumes fewer tokens).
  case detailLow // = 2

  /// The model will process a high-resolution of the image. This is slower and
  /// more expensive but will allow the model to attend to more nuanced details
  /// in the image.
  case detailHigh // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .detailInvalid
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .detailInvalid
    case 1: self = .detailAuto
    case 2: self = .detailLow
    case 3: self = .detailHigh
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .detailInvalid: return 0
    case .detailAuto: return 1
    case .detailLow: return 2
    case .detailHigh: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_ImageDetail] = [
    .detailInvalid,
    .detailAuto,
    .detailLow,
    .detailHigh,
  ]

}

/// The image format to be returned (base-64 encoded string or a url of
/// the image).
public enum XaiApi_ImageFormat: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Image format is invalid.
  case imgFormatInvalid // = 0

  /// A base-64 encoding of the image.
  case imgFormatBase64 // = 1

  /// An URL at which the user can download the image.
  case imgFormatURL // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .imgFormatInvalid
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .imgFormatInvalid
    case 1: self = .imgFormatBase64
    case 2: self = .imgFormatURL
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .imgFormatInvalid: return 0
    case .imgFormatBase64: return 1
    case .imgFormatURL: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_ImageFormat] = [
    .imgFormatInvalid,
    .imgFormatBase64,
    .imgFormatURL,
  ]

}

/// Quality levels for image generation with their corresponding resolutions.
/// Currently only supported by grok-imagine models.
public enum XaiApi_ImageQuality: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Quality is invalid.
  case imgQualityInvalid // = 0

  /// Low quality.
  case imgQualityLow // = 1

  /// Medium quality: (default).
  case imgQualityMedium // = 2

  /// High quality.
  case imgQualityHigh // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .imgQualityInvalid
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .imgQualityInvalid
    case 1: self = .imgQualityLow
    case 2: self = .imgQualityMedium
    case 3: self = .imgQualityHigh
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .imgQualityInvalid: return 0
    case .imgQualityLow: return 1
    case .imgQualityMedium: return 2
    case .imgQualityHigh: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_ImageQuality] = [
    .imgQualityInvalid,
    .imgQualityLow,
    .imgQualityMedium,
    .imgQualityHigh,
  ]

}

/// Aspect ratio for image generation.
/// Only supported by grok-imagine models.
public enum XaiApi_ImageAspectRatio: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Invalid aspect ratio.
  case imgAspectRatioInvalid // = 0

  /// 1:1 aspect ratio (square).
  case imgAspectRatio11 // = 1

  /// 3:4 aspect ratio (portrait).
  case imgAspectRatio34 // = 2

  /// 4:3 aspect ratio (landscape).
  case imgAspectRatio43 // = 3

  /// 9:16 aspect ratio (tall portrait).
  case imgAspectRatio916 // = 4

  /// 16:9 aspect ratio (wide landscape).
  case imgAspectRatio169 // = 5

  /// 2:3 aspect ratio (photo portrait).
  case imgAspectRatio23 // = 6

  /// 3:2 aspect ratio (photo landscape).
  case imgAspectRatio32 // = 7

  /// Auto aspect ratio (model auto-selects based on prompt).
  /// Only supported for image generation with a thinking upsampler.
  case imgAspectRatioAuto // = 8

  /// 9:19.5 aspect ratio (extra tall portrait - phone screens).
  case imgAspectRatio9195 // = 9

  /// 19.5:9 aspect ratio (extra wide landscape).
  case imgAspectRatio1959 // = 10

  /// 9:20 aspect ratio (tall portrait - modern phone screens).
  case imgAspectRatio920 // = 11

  /// 20:9 aspect ratio (ultra wide landscape).
  case imgAspectRatio209 // = 12

  /// 1:2 aspect ratio (tall portrait).
  case imgAspectRatio12 // = 13

  /// 2:1 aspect ratio (wide landscape).
  case imgAspectRatio21 // = 14
  case UNRECOGNIZED(Int)

  public init() {
    self = .imgAspectRatioInvalid
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .imgAspectRatioInvalid
    case 1: self = .imgAspectRatio11
    case 2: self = .imgAspectRatio34
    case 3: self = .imgAspectRatio43
    case 4: self = .imgAspectRatio916
    case 5: self = .imgAspectRatio169
    case 6: self = .imgAspectRatio23
    case 7: self = .imgAspectRatio32
    case 8: self = .imgAspectRatioAuto
    case 9: self = .imgAspectRatio9195
    case 10: self = .imgAspectRatio1959
    case 11: self = .imgAspectRatio920
    case 12: self = .imgAspectRatio209
    case 13: self = .imgAspectRatio12
    case 14: self = .imgAspectRatio21
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .imgAspectRatioInvalid: return 0
    case .imgAspectRatio11: return 1
    case .imgAspectRatio34: return 2
    case .imgAspectRatio43: return 3
    case .imgAspectRatio916: return 4
    case .imgAspectRatio169: return 5
    case .imgAspectRatio23: return 6
    case .imgAspectRatio32: return 7
    case .imgAspectRatioAuto: return 8
    case .imgAspectRatio9195: return 9
    case .imgAspectRatio1959: return 10
    case .imgAspectRatio920: return 11
    case .imgAspectRatio209: return 12
    case .imgAspectRatio12: return 13
    case .imgAspectRatio21: return 14
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_ImageAspectRatio] = [
    .imgAspectRatioInvalid,
    .imgAspectRatio11,
    .imgAspectRatio34,
    .imgAspectRatio43,
    .imgAspectRatio916,
    .imgAspectRatio169,
    .imgAspectRatio23,
    .imgAspectRatio32,
    .imgAspectRatioAuto,
    .imgAspectRatio9195,
    .imgAspectRatio1959,
    .imgAspectRatio920,
    .imgAspectRatio209,
    .imgAspectRatio12,
    .imgAspectRatio21,
  ]

}

/// Resolution for image generation.
/// Only supported by grok-imagine models.
public enum XaiApi_ImageResolution: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Invalid resolution.
  case imgResolutionInvalid // = 0

  /// 1k resolution (~1 megapixel total).
  /// Dimensions vary by aspect ratio.
  case imgResolution1K // = 1

  /// 2k resolution (~4 megapixel total).
  case imgResolution2K // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .imgResolutionInvalid
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .imgResolutionInvalid
    case 1: self = .imgResolution1K
    case 2: self = .imgResolution2K
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .imgResolutionInvalid: return 0
    case .imgResolution1K: return 1
    case .imgResolution2K: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_ImageResolution] = [
    .imgResolutionInvalid,
    .imgResolution1K,
    .imgResolution2K,
  ]

}

/// Request message for generating an image.
public struct XaiApi_GenerateImageRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Input prompt to generate an image from.
  public var prompt: String = String()

  /// Optional input image to perform generations based on.
  public var image: XaiApi_ImageUrlContent {
    get {_image ?? XaiApi_ImageUrlContent()}
    set {_image = newValue}
  }
  /// Returns true if `image` has been explicitly set.
  public var hasImage: Bool {self._image != nil}
  /// Clears the value of `image`. Subsequent reads from it will return its default value.
  public mutating func clearImage() {self._image = nil}

  /// Name or alias of the image generation model to be used.
  public var model: String = String()

  /// Number of images to generate. Allowed values are [1, 10].
  public var n: Int32 {
    get {_n ?? 0}
    set {_n = newValue}
  }
  /// Returns true if `n` has been explicitly set.
  public var hasN: Bool {self._n != nil}
  /// Clears the value of `n`. Subsequent reads from it will return its default value.
  public mutating func clearN() {self._n = nil}

  /// An opaque string supplied by the API client (customer) to identify a user.
  /// The string will be stored in the logs and can be used in customer service
  /// requests to identify certain requests.
  public var user: String = String()

  /// Optional field to specify the image format to return the generated image(s)
  /// in. See ImageFormat enum for options.
  public var format: XaiApi_ImageFormat = .imgFormatInvalid

  /// Optional aspect ratio for image generation/editing.
  /// Only supported by grok-imagine models.
  /// Defaults to 1:1 if not specified. Auto is only supported for image generation
  /// with a thinking upsampler.
  public var aspectRatio: XaiApi_ImageAspectRatio {
    get {_aspectRatio ?? .imgAspectRatioInvalid}
    set {_aspectRatio = newValue}
  }
  /// Returns true if `aspectRatio` has been explicitly set.
  public var hasAspectRatio: Bool {self._aspectRatio != nil}
  /// Clears the value of `aspectRatio`. Subsequent reads from it will return its default value.
  public mutating func clearAspectRatio() {self._aspectRatio = nil}

  /// Optional resolution for image generation/editing.
  /// Only supported by grok-imagine models.
  /// Defaults to 1k if not specified.
  /// When 2k is selected, the image is generated at 1k and upscaled using super-resolution.
  /// The final output area is capped at approximately 2048x2048 pixels, with dimensions
  /// adjusted to preserve aspect ratio and rounded to multiples of 16.
  public var resolution: XaiApi_ImageResolution {
    get {_resolution ?? .imgResolutionInvalid}
    set {_resolution = newValue}
  }
  /// Returns true if `resolution` has been explicitly set.
  public var hasResolution: Bool {self._resolution != nil}
  /// Clears the value of `resolution`. Subsequent reads from it will return its default value.
  public mutating func clearResolution() {self._resolution = nil}

  /// Optional list of input images for multi-reference image editing.
  /// Each image is either an image URL or a base64-encoded version of the image.
  /// This field cannot be set together with the `image` field.
  public var images: [XaiApi_ImageUrlContent] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _image: XaiApi_ImageUrlContent? = nil
  fileprivate var _n: Int32? = nil
  fileprivate var _aspectRatio: XaiApi_ImageAspectRatio? = nil
  fileprivate var _resolution: XaiApi_ImageResolution? = nil
}

/// The response from the image generation models containing the generated image(s).
public struct XaiApi_ImageResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A list of generated images (including relevant metadata).
  public var images: [XaiApi_GeneratedImage] = []

  /// The model used to generate the image (ignoring aliases).
  public var model: String = String()

  /// The usage of the request.
  public var usage: XaiApi_SamplingUsage {
    get {_usage ?? XaiApi_SamplingUsage()}
    set {_usage = newValue}
  }
  /// Returns true if `usage` has been explicitly set.
  public var hasUsage: Bool {self._usage != nil}
  /// Clears the value of `usage`. Subsequent reads from it will return its default value.
  public mutating func clearUsage() {self._usage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _usage: XaiApi_SamplingUsage? = nil
}

/// Contains all data related to a generated image.
public struct XaiApi_GeneratedImage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The generated image.
  public var image: XaiApi_GeneratedImage.OneOf_Image? = nil

  /// A base-64 encoded string of the image. Provided if user specified `IMG_FORMAT_BASE64` in `format` field of the
  /// `GenerateImageRequest` message.
  public var base64: String {
    get {
      if case .base64(let v)? = image {return v}
      return String()
    }
    set {image = .base64(newValue)}
  }

  /// A url that points to the generated image. Provided if user specified `IMG_FORMAT_URL` in `format` field of the
  /// `GenerateImageRequest` message.
  public var url: String {
    get {
      if case .url(let v)? = image {return v}
      return String()
    }
    set {image = .url(newValue)}
  }

  /// Whether the image generated by the model respects moderation rules.
  /// The field will be true if the image respect moderation rules. Otherwise
  /// the field will be false and the image field is replaced by a placeholder.
  public var respectModeration: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The generated image.
  public enum OneOf_Image: Equatable, Sendable {
    /// A base-64 encoded string of the image. Provided if user specified `IMG_FORMAT_BASE64` in `format` field of the
    /// `GenerateImageRequest` message.
    case base64(String)
    /// A url that points to the generated image. Provided if user specified `IMG_FORMAT_URL` in `format` field of the
    /// `GenerateImageRequest` message.
    case url(String)

  }

  public init() {}
}

/// Contains data relating to an image that is provided to the model.
public struct XaiApi_ImageUrlContent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// This is either an image URL or a base64-encoded version of the image.
  /// The following image formats are supported: PNG, JPG, and WebP.
  /// If an image URL is provided, the image will be downloaded for every API
  /// request without being cached. Images are fetched using
  /// "XaiImageApiFetch/1.0" user agent, and will timeout after 5 seconds.
  /// The image size is limited to 10 MiB. If the image download fails, the API
  /// request will fail as well.
  public var imageURL: String = String()

  /// The level of pre-processing resolution that will be applied to the image.
  public var detail: XaiApi_ImageDetail = .detailInvalid

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xai_api"

extension XaiApi_ImageDetail: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DETAIL_INVALID\0\u{1}DETAIL_AUTO\0\u{1}DETAIL_LOW\0\u{1}DETAIL_HIGH\0")
}

extension XaiApi_ImageFormat: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0IMG_FORMAT_INVALID\0\u{1}IMG_FORMAT_BASE64\0\u{1}IMG_FORMAT_URL\0")
}

extension XaiApi_ImageQuality: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0IMG_QUALITY_INVALID\0\u{1}IMG_QUALITY_LOW\0\u{1}IMG_QUALITY_MEDIUM\0\u{1}IMG_QUALITY_HIGH\0")
}

extension XaiApi_ImageAspectRatio: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0IMG_ASPECT_RATIO_INVALID\0\u{1}IMG_ASPECT_RATIO_1_1\0\u{1}IMG_ASPECT_RATIO_3_4\0\u{1}IMG_ASPECT_RATIO_4_3\0\u{1}IMG_ASPECT_RATIO_9_16\0\u{1}IMG_ASPECT_RATIO_16_9\0\u{1}IMG_ASPECT_RATIO_2_3\0\u{1}IMG_ASPECT_RATIO_3_2\0\u{1}IMG_ASPECT_RATIO_AUTO\0\u{1}IMG_ASPECT_RATIO_9_19_5\0\u{1}IMG_ASPECT_RATIO_19_5_9\0\u{1}IMG_ASPECT_RATIO_9_20\0\u{1}IMG_ASPECT_RATIO_20_9\0\u{1}IMG_ASPECT_RATIO_1_2\0\u{1}IMG_ASPECT_RATIO_2_1\0")
}

extension XaiApi_ImageResolution: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0IMG_RESOLUTION_INVALID\0\u{1}IMG_RESOLUTION_1K\0\u{1}IMG_RESOLUTION_2K\0")
}

extension XaiApi_GenerateImageRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GenerateImageRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}prompt\0\u{1}model\0\u{1}n\0\u{1}user\0\u{1}image\0\u{2}\u{6}format\0\u{4}\u{3}aspect_ratio\0\u{1}resolution\0\u{2}\u{2}images\0\u{c}\u{d}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.prompt) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._n) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.user) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._image) }()
      case 11: try { try decoder.decodeSingularEnumField(value: &self.format) }()
      case 14: try { try decoder.decodeSingularEnumField(value: &self._aspectRatio) }()
      case 15: try { try decoder.decodeSingularEnumField(value: &self._resolution) }()
      case 17: try { try decoder.decodeRepeatedMessageField(value: &self.images) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.prompt.isEmpty {
      try visitor.visitSingularStringField(value: self.prompt, fieldNumber: 1)
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 2)
    }
    try { if let v = self._n {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    if !self.user.isEmpty {
      try visitor.visitSingularStringField(value: self.user, fieldNumber: 4)
    }
    try { if let v = self._image {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if self.format != .imgFormatInvalid {
      try visitor.visitSingularEnumField(value: self.format, fieldNumber: 11)
    }
    try { if let v = self._aspectRatio {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 14)
    } }()
    try { if let v = self._resolution {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 15)
    } }()
    if !self.images.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.images, fieldNumber: 17)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GenerateImageRequest, rhs: XaiApi_GenerateImageRequest) -> Bool {
    if lhs.prompt != rhs.prompt {return false}
    if lhs._image != rhs._image {return false}
    if lhs.model != rhs.model {return false}
    if lhs._n != rhs._n {return false}
    if lhs.user != rhs.user {return false}
    if lhs.format != rhs.format {return false}
    if lhs._aspectRatio != rhs._aspectRatio {return false}
    if lhs._resolution != rhs._resolution {return false}
    if lhs.images != rhs.images {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ImageResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImageResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}images\0\u{1}model\0\u{1}usage\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.images) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._usage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.images.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.images, fieldNumber: 1)
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 2)
    }
    try { if let v = self._usage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ImageResponse, rhs: XaiApi_ImageResponse) -> Bool {
    if lhs.images != rhs.images {return false}
    if lhs.model != rhs.model {return false}
    if lhs._usage != rhs._usage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_GeneratedImage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GeneratedImage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}base64\0\u{2}\u{2}url\0\u{3}respect_moderation\0\u{c}\u{2}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.image != nil {try decoder.handleConflictingOneOf()}
          self.image = .base64(v)
        }
      }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.image != nil {try decoder.handleConflictingOneOf()}
          self.image = .url(v)
        }
      }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.respectModeration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.image {
    case .base64?: try {
      guard case .base64(let v)? = self.image else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .url?: try {
      guard case .url(let v)? = self.image else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case nil: break
    }
    if self.respectModeration != false {
      try visitor.visitSingularBoolField(value: self.respectModeration, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GeneratedImage, rhs: XaiApi_GeneratedImage) -> Bool {
    if lhs.image != rhs.image {return false}
    if lhs.respectModeration != rhs.respectModeration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ImageUrlContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImageUrlContent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}image_url\0\u{1}detail\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.imageURL) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.detail) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.imageURL.isEmpty {
      try visitor.visitSingularStringField(value: self.imageURL, fieldNumber: 1)
    }
    if self.detail != .detailInvalid {
      try visitor.visitSingularEnumField(value: self.detail, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ImageUrlContent, rhs: XaiApi_ImageUrlContent) -> Bool {
    if lhs.imageURL != rhs.imageURL {return false}
    if lhs.detail != rhs.detail {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
