// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Modalities supported by a model input/output.
public enum XaiApi_Modality: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Invalid modality.
  case invalidModality // = 0

  /// Text input/output.
  case text // = 1

  /// Image input/output.
  case image // = 2

  /// Embedding input/output.
  case embedding // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .invalidModality
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .invalidModality
    case 1: self = .text
    case 2: self = .image
    case 3: self = .embedding
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .invalidModality: return 0
    case .text: return 1
    case .image: return 2
    case .embedding: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_Modality] = [
    .invalidModality,
    .text,
    .image,
    .embedding,
  ]

}

/// Request to get details of a specific model by name.
public struct XaiApi_GetModelRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the model to retrieve details about.
  public var name: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Describes a language model available on the platform.
public struct XaiApi_LanguageModel: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The model name used in API requests/responses.
  public var name: String = String()

  /// The aliases of the name, which can also be used in lieu of name in the API
  /// requests.
  public var aliases: [String] = []

  /// The version number of this model. Used to identify minor updates when
  /// the model name is not changed.
  public var version: String = String()

  /// The supported input modalities of the model.
  public var inputModalities: [XaiApi_Modality] = []

  /// The supported output modalities of the model.
  public var outputModalities: [XaiApi_Modality] = []

  /// The price (in 1/100 USD cents) per one million text prompt tokens.
  public var promptTextTokenPrice: Int64 = 0

  /// The price (in 1/100 USD cents) per one million image prompt tokens.
  public var promptImageTokenPrice: Int64 = 0

  /// The price (in USD cents) per 100 million cached text prompt tokens.
  public var cachedPromptTokenPrice: Int64 = 0

  /// The price (in 1/100 USD cents) per one million text completion token.
  public var completionTextTokenPrice: Int64 = 0

  /// The price (in 1/100 USD cents) per one million searches.
  public var searchPrice: Int64 = 0

  /// The creation time of the model.
  public var created: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_created ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_created = newValue}
  }
  /// Returns true if `created` has been explicitly set.
  public var hasCreated: Bool {self._created != nil}
  /// Clears the value of `created`. Subsequent reads from it will return its default value.
  public mutating func clearCreated() {self._created = nil}

  /// Maximum length of the prompt/input (this includes tokens of all kinds).
  /// This is typically known as the context length of the model.
  public var maxPromptLength: Int32 = 0

  /// Fingerprint of the unique configuration of the model.
  public var systemFingerprint: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _created: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// Response from ListLanguageModels including a list of language models.
public struct XaiApi_ListLanguageModelsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A list of language models.
  public var models: [XaiApi_LanguageModel] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Describes an embedding model available on the platform.
public struct XaiApi_EmbeddingModel: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name under which the model is available in the API.
  public var name: String = String()

  /// The aliases of the name, which can also be used in lieu of name in the API
  /// requests.
  public var aliases: [String] = []

  /// The version number of this model. Used to identify minor updates when
  /// the model name is not changed.
  public var version: String = String()

  /// The supported input modalities of the model.
  public var inputModalities: [XaiApi_Modality] = []

  /// The supported output modalities of the model.
  public var outputModalities: [XaiApi_Modality] = []

  /// The price (in 1/100 USD cents) per one million text prompt tokens.
  public var promptTextTokenPrice: Int64 = 0

  /// The price (in 1/100 USD cents) per one million image prompt tokens.
  public var promptImageTokenPrice: Int64 = 0

  /// The creation time of the model.
  public var created: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_created ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_created = newValue}
  }
  /// Returns true if `created` has been explicitly set.
  public var hasCreated: Bool {self._created != nil}
  /// Clears the value of `created`. Subsequent reads from it will return its default value.
  public mutating func clearCreated() {self._created = nil}

  /// Fingerprint of the unique configuration of the model.
  public var systemFingerprint: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _created: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// Response from ListEmbeddingModels including a list of embedding models.
public struct XaiApi_ListEmbeddingModelsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A list of embedding model(s).
  public var models: [XaiApi_EmbeddingModel] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Describes a language model available on the platform.
public struct XaiApi_ImageGenerationModel: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The model name used in API requests/responses.
  public var name: String = String()

  /// The aliases of the name, which can also be used in lieu of name in the API
  /// requests.
  public var aliases: [String] = []

  /// The version number of this model. Used to identify minor updates when
  /// the model name is not changed.
  public var version: String = String()

  /// The supported input modalities of the model.
  public var inputModalities: [XaiApi_Modality] = []

  /// The supported output modalities of the model.
  public var outputModalities: [XaiApi_Modality] = []

  /// The price (in USD cents) per image.
  public var imagePrice: Int64 = 0

  /// When the language model was created.
  public var created: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_created ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_created = newValue}
  }
  /// Returns true if `created` has been explicitly set.
  public var hasCreated: Bool {self._created != nil}
  /// Clears the value of `created`. Subsequent reads from it will return its default value.
  public mutating func clearCreated() {self._created = nil}

  /// Maximum length of the prompt/input (this includes tokens of all kinds).
  /// This is typically known as the context length of the model.
  public var maxPromptLength: Int32 = 0

  /// Fingerprint of the unique configuration of the model.
  public var systemFingerprint: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _created: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// Response from ListImageGenerationModels including a list of image generation
/// models.
public struct XaiApi_ListImageGenerationModelsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A list of image generation models.
  public var models: [XaiApi_ImageGenerationModel] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xai_api"

extension XaiApi_Modality: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INVALID_MODALITY\0\u{1}TEXT\0\u{1}IMAGE\0\u{1}EMBEDDING\0")
}

extension XaiApi_GetModelRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetModelRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GetModelRequest, rhs: XaiApi_GetModelRequest) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_LanguageModel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LanguageModel"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}version\0\u{3}input_modalities\0\u{3}output_modalities\0\u{3}prompt_text_token_price\0\u{3}prompt_image_token_price\0\u{3}completion_text_token_price\0\u{1}created\0\u{3}max_prompt_length\0\u{3}system_fingerprint\0\u{1}aliases\0\u{3}cached_prompt_token_price\0\u{3}search_price\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 3: try { try decoder.decodeRepeatedEnumField(value: &self.inputModalities) }()
      case 4: try { try decoder.decodeRepeatedEnumField(value: &self.outputModalities) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.promptTextTokenPrice) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.promptImageTokenPrice) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.completionTextTokenPrice) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._created) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.maxPromptLength) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.systemFingerprint) }()
      case 11: try { try decoder.decodeRepeatedStringField(value: &self.aliases) }()
      case 12: try { try decoder.decodeSingularInt64Field(value: &self.cachedPromptTokenPrice) }()
      case 13: try { try decoder.decodeSingularInt64Field(value: &self.searchPrice) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 2)
    }
    if !self.inputModalities.isEmpty {
      try visitor.visitPackedEnumField(value: self.inputModalities, fieldNumber: 3)
    }
    if !self.outputModalities.isEmpty {
      try visitor.visitPackedEnumField(value: self.outputModalities, fieldNumber: 4)
    }
    if self.promptTextTokenPrice != 0 {
      try visitor.visitSingularInt64Field(value: self.promptTextTokenPrice, fieldNumber: 5)
    }
    if self.promptImageTokenPrice != 0 {
      try visitor.visitSingularInt64Field(value: self.promptImageTokenPrice, fieldNumber: 6)
    }
    if self.completionTextTokenPrice != 0 {
      try visitor.visitSingularInt64Field(value: self.completionTextTokenPrice, fieldNumber: 7)
    }
    try { if let v = self._created {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if self.maxPromptLength != 0 {
      try visitor.visitSingularInt32Field(value: self.maxPromptLength, fieldNumber: 9)
    }
    if !self.systemFingerprint.isEmpty {
      try visitor.visitSingularStringField(value: self.systemFingerprint, fieldNumber: 10)
    }
    if !self.aliases.isEmpty {
      try visitor.visitRepeatedStringField(value: self.aliases, fieldNumber: 11)
    }
    if self.cachedPromptTokenPrice != 0 {
      try visitor.visitSingularInt64Field(value: self.cachedPromptTokenPrice, fieldNumber: 12)
    }
    if self.searchPrice != 0 {
      try visitor.visitSingularInt64Field(value: self.searchPrice, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_LanguageModel, rhs: XaiApi_LanguageModel) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.aliases != rhs.aliases {return false}
    if lhs.version != rhs.version {return false}
    if lhs.inputModalities != rhs.inputModalities {return false}
    if lhs.outputModalities != rhs.outputModalities {return false}
    if lhs.promptTextTokenPrice != rhs.promptTextTokenPrice {return false}
    if lhs.promptImageTokenPrice != rhs.promptImageTokenPrice {return false}
    if lhs.cachedPromptTokenPrice != rhs.cachedPromptTokenPrice {return false}
    if lhs.completionTextTokenPrice != rhs.completionTextTokenPrice {return false}
    if lhs.searchPrice != rhs.searchPrice {return false}
    if lhs._created != rhs._created {return false}
    if lhs.maxPromptLength != rhs.maxPromptLength {return false}
    if lhs.systemFingerprint != rhs.systemFingerprint {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListLanguageModelsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListLanguageModelsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}models\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.models) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.models.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.models, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListLanguageModelsResponse, rhs: XaiApi_ListLanguageModelsResponse) -> Bool {
    if lhs.models != rhs.models {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_EmbeddingModel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EmbeddingModel"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}version\0\u{3}input_modalities\0\u{3}output_modalities\0\u{3}prompt_text_token_price\0\u{3}prompt_image_token_price\0\u{1}created\0\u{3}system_fingerprint\0\u{2}\u{3}aliases\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 3: try { try decoder.decodeRepeatedEnumField(value: &self.inputModalities) }()
      case 4: try { try decoder.decodeRepeatedEnumField(value: &self.outputModalities) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.promptTextTokenPrice) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.promptImageTokenPrice) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._created) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.systemFingerprint) }()
      case 11: try { try decoder.decodeRepeatedStringField(value: &self.aliases) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 2)
    }
    if !self.inputModalities.isEmpty {
      try visitor.visitPackedEnumField(value: self.inputModalities, fieldNumber: 3)
    }
    if !self.outputModalities.isEmpty {
      try visitor.visitPackedEnumField(value: self.outputModalities, fieldNumber: 4)
    }
    if self.promptTextTokenPrice != 0 {
      try visitor.visitSingularInt64Field(value: self.promptTextTokenPrice, fieldNumber: 5)
    }
    if self.promptImageTokenPrice != 0 {
      try visitor.visitSingularInt64Field(value: self.promptImageTokenPrice, fieldNumber: 6)
    }
    try { if let v = self._created {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    if !self.systemFingerprint.isEmpty {
      try visitor.visitSingularStringField(value: self.systemFingerprint, fieldNumber: 8)
    }
    if !self.aliases.isEmpty {
      try visitor.visitRepeatedStringField(value: self.aliases, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_EmbeddingModel, rhs: XaiApi_EmbeddingModel) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.aliases != rhs.aliases {return false}
    if lhs.version != rhs.version {return false}
    if lhs.inputModalities != rhs.inputModalities {return false}
    if lhs.outputModalities != rhs.outputModalities {return false}
    if lhs.promptTextTokenPrice != rhs.promptTextTokenPrice {return false}
    if lhs.promptImageTokenPrice != rhs.promptImageTokenPrice {return false}
    if lhs._created != rhs._created {return false}
    if lhs.systemFingerprint != rhs.systemFingerprint {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListEmbeddingModelsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListEmbeddingModelsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}models\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.models) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.models.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.models, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListEmbeddingModelsResponse, rhs: XaiApi_ListEmbeddingModelsResponse) -> Bool {
    if lhs.models != rhs.models {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ImageGenerationModel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ImageGenerationModel"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}version\0\u{3}input_modalities\0\u{4}\u{3}output_modalities\0\u{2}\u{2}created\0\u{3}max_prompt_length\0\u{3}system_fingerprint\0\u{1}aliases\0\u{3}image_price\0\u{c}\u{4}\u{1}\u{c}\u{5}\u{1}\u{c}\u{7}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.version) }()
      case 3: try { try decoder.decodeRepeatedEnumField(value: &self.inputModalities) }()
      case 6: try { try decoder.decodeRepeatedEnumField(value: &self.outputModalities) }()
      case 8: try { try decoder.decodeSingularMessageField(value: &self._created) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.maxPromptLength) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.systemFingerprint) }()
      case 11: try { try decoder.decodeRepeatedStringField(value: &self.aliases) }()
      case 12: try { try decoder.decodeSingularInt64Field(value: &self.imagePrice) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 2)
    }
    if !self.inputModalities.isEmpty {
      try visitor.visitPackedEnumField(value: self.inputModalities, fieldNumber: 3)
    }
    if !self.outputModalities.isEmpty {
      try visitor.visitPackedEnumField(value: self.outputModalities, fieldNumber: 6)
    }
    try { if let v = self._created {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    } }()
    if self.maxPromptLength != 0 {
      try visitor.visitSingularInt32Field(value: self.maxPromptLength, fieldNumber: 9)
    }
    if !self.systemFingerprint.isEmpty {
      try visitor.visitSingularStringField(value: self.systemFingerprint, fieldNumber: 10)
    }
    if !self.aliases.isEmpty {
      try visitor.visitRepeatedStringField(value: self.aliases, fieldNumber: 11)
    }
    if self.imagePrice != 0 {
      try visitor.visitSingularInt64Field(value: self.imagePrice, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ImageGenerationModel, rhs: XaiApi_ImageGenerationModel) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.aliases != rhs.aliases {return false}
    if lhs.version != rhs.version {return false}
    if lhs.inputModalities != rhs.inputModalities {return false}
    if lhs.outputModalities != rhs.outputModalities {return false}
    if lhs.imagePrice != rhs.imagePrice {return false}
    if lhs._created != rhs._created {return false}
    if lhs.maxPromptLength != rhs.maxPromptLength {return false}
    if lhs.systemFingerprint != rhs.systemFingerprint {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_ListImageGenerationModelsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ListImageGenerationModelsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}models\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.models) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.models.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.models, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_ListImageGenerationModelsResponse, rhs: XaiApi_ListImageGenerationModelsResponse) -> Bool {
    if lhs.models != rhs.models {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
