// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/sample.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Reasons why the model stopped sampling.
public enum XaiApi_FinishReason: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Invalid reason.
  case reasonInvalid // = 0

  /// The max_len parameter specified on the input is reached.
  case reasonMaxLen // = 1

  /// The maximum context length of the model is reached.
  case reasonMaxContext // = 2

  /// One of the stop words was found.
  case reasonStop // = 3

  /// A tool call is included in the response.
  case reasonToolCalls // = 4

  /// Time limit has been reached.
  case reasonTimeLimit // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .reasonInvalid
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .reasonInvalid
    case 1: self = .reasonMaxLen
    case 2: self = .reasonMaxContext
    case 3: self = .reasonStop
    case 4: self = .reasonToolCalls
    case 5: self = .reasonTimeLimit
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .reasonInvalid: return 0
    case .reasonMaxLen: return 1
    case .reasonMaxContext: return 2
    case .reasonStop: return 3
    case .reasonToolCalls: return 4
    case .reasonTimeLimit: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_FinishReason] = [
    .reasonInvalid,
    .reasonMaxLen,
    .reasonMaxContext,
    .reasonStop,
    .reasonToolCalls,
    .reasonTimeLimit,
  ]

}

/// Request to get a text completion response sampling.
public struct XaiApi_SampleTextRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Text prompts to sample on.
  public var prompt: [String] = []

  /// Name or alias of the model to be used.
  public var model: String = String()

  /// The number of completions to create concurrently. A single completion will
  /// be generated if the parameter is unset. Each completion is charged at the
  /// same rate. You can generate at most 128 concurrent completions.
  public var n: Int32 {
    get {_n ?? 0}
    set {_n = newValue}
  }
  /// Returns true if `n` has been explicitly set.
  public var hasN: Bool {self._n != nil}
  /// Clears the value of `n`. Subsequent reads from it will return its default value.
  public mutating func clearN() {self._n = nil}

  /// The maximum number of tokens to sample. If unset, the model samples until
  /// one of the following stop-conditions is reached:
  /// - The context length of the model is exceeded
  /// - One of the `stop` sequences has been observed.
  ///
  /// We recommend choosing a reasonable value to reduce the risk of accidental
  /// long-generations that consume many tokens.
  public var maxTokens: Int32 {
    get {_maxTokens ?? 0}
    set {_maxTokens = newValue}
  }
  /// Returns true if `maxTokens` has been explicitly set.
  public var hasMaxTokens: Bool {self._maxTokens != nil}
  /// Clears the value of `maxTokens`. Subsequent reads from it will return its default value.
  public mutating func clearMaxTokens() {self._maxTokens = nil}

  /// A random seed used to make the sampling process deterministic. This is
  /// provided in a best-effort basis without guarantee that sampling is 100%
  /// deterministic given a seed. This is primarily provided for short-lived
  /// testing purposes. Given a fixed request and seed, the answers may change
  /// over time as our systems evolve.
  public var seed: Int32 {
    get {_seed ?? 0}
    set {_seed = newValue}
  }
  /// Returns true if `seed` has been explicitly set.
  public var hasSeed: Bool {self._seed != nil}
  /// Clears the value of `seed`. Subsequent reads from it will return its default value.
  public mutating func clearSeed() {self._seed = nil}

  /// String patterns that will cause the sampling procedure to stop prematurely
  /// when observed.
  /// Note that the completion is based on individual tokens and sampling can
  /// only terminate at token boundaries. If a stop string is a substring of an
  /// individual token, the completion will include the entire token, which
  /// extends beyond the stop string.
  /// For example, if `stop = ["wor"]` and we prompt the model with "hello" to
  /// which it responds with "world", then the sampling procedure will stop after
  /// observing the "world" token and the completion will contain
  /// the entire world "world" even though the stop string was just "wor".
  /// You can provide at most 8 stop strings.
  public var stop: [String] = []

  /// A number between 0 and 2 used to control the variance of completions.
  /// The smaller the value, the more deterministic the model will become. For
  /// example, if we sample 1000 answers to the same prompt at a temperature of
  /// 0.001, then most of the 1000 answers will be identical. Conversely, if we
  /// conduct the same experiment at a temperature of 2, virtually no two answers
  /// will be identical. Note that increasing the temperature will cause
  /// the model to hallucinate more strongly.
  public var temperature: Float {
    get {_temperature ?? 0}
    set {_temperature = newValue}
  }
  /// Returns true if `temperature` has been explicitly set.
  public var hasTemperature: Bool {self._temperature != nil}
  /// Clears the value of `temperature`. Subsequent reads from it will return its default value.
  public mutating func clearTemperature() {self._temperature = nil}

  /// A number between 0 and 1 controlling the likelihood of the model to use
  /// less-common answers. Recall that the model produces a probability for
  /// each token. This means, for any choice of token there are thousands of
  /// possibilities to choose from. This parameter controls the "nucleus sampling
  /// algorithm". Instead of considering every possible token at every step, we
  /// only look at the K tokens who's probabilities exceed `top_p`.
  /// For example, if we set `top_p = 0.9`, then the set of tokens we actually
  /// sample from, will have a probability mass of at least 90%. In practice,
  /// low values will make the model more deterministic.
  public var topP: Float {
    get {_topP ?? 0}
    set {_topP = newValue}
  }
  /// Returns true if `topP` has been explicitly set.
  public var hasTopP: Bool {self._topP != nil}
  /// Clears the value of `topP`. Subsequent reads from it will return its default value.
  public mutating func clearTopP() {self._topP = nil}

  /// Number between -2.0 and 2.0.
  /// Positive values penalize new tokens based on their existing frequency in the text so far,
  /// decreasing the model's likelihood to repeat the same line verbatim.
  public var frequencyPenalty: Float {
    get {_frequencyPenalty ?? 0}
    set {_frequencyPenalty = newValue}
  }
  /// Returns true if `frequencyPenalty` has been explicitly set.
  public var hasFrequencyPenalty: Bool {self._frequencyPenalty != nil}
  /// Clears the value of `frequencyPenalty`. Subsequent reads from it will return its default value.
  public mutating func clearFrequencyPenalty() {self._frequencyPenalty = nil}

  /// Whether to return log probabilities of the output tokens or not.
  /// If true, returns the log probabilities of each output token returned in the content of message.
  public var logprobs: Bool = false

  /// Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
  /// Not supported by grok-3 models.
  public var presencePenalty: Float {
    get {_presencePenalty ?? 0}
    set {_presencePenalty = newValue}
  }
  /// Returns true if `presencePenalty` has been explicitly set.
  public var hasPresencePenalty: Bool {self._presencePenalty != nil}
  /// Clears the value of `presencePenalty`. Subsequent reads from it will return its default value.
  public mutating func clearPresencePenalty() {self._presencePenalty = nil}

  /// An integer between 0 and 8 specifying the number of most likely tokens to return at each token position,
  /// each with an associated log probability.
  /// logprobs must be set to true if this parameter is used.
  public var topLogprobs: Int32 {
    get {_topLogprobs ?? 0}
    set {_topLogprobs = newValue}
  }
  /// Returns true if `topLogprobs` has been explicitly set.
  public var hasTopLogprobs: Bool {self._topLogprobs != nil}
  /// Clears the value of `topLogprobs`. Subsequent reads from it will return its default value.
  public mutating func clearTopLogprobs() {self._topLogprobs = nil}

  /// An opaque string supplied by the API client (customer) to identify a user.
  /// The string will be stored in the logs and can be used in customer service
  /// requests to identify certain requests.
  public var user: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _n: Int32? = nil
  fileprivate var _maxTokens: Int32? = nil
  fileprivate var _seed: Int32? = nil
  fileprivate var _temperature: Float? = nil
  fileprivate var _topP: Float? = nil
  fileprivate var _frequencyPenalty: Float? = nil
  fileprivate var _presencePenalty: Float? = nil
  fileprivate var _topLogprobs: Int32? = nil
}

/// Response of a text completion response sampling.
public struct XaiApi_SampleTextResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of this request. This ID will also show up on your billing records
  /// and you can use it when contacting us regarding a specific request.
  public var id: String = String()

  /// Completions in response to the input messages. The number of completions is
  /// controlled via the `n` parameter on the request.
  public var choices: [XaiApi_SampleChoice] = []

  /// A UNIX timestamp (UTC) indicating when the response object was created.
  /// The timestamp is taken when the model starts generating response.
  public var created: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_created ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_created = newValue}
  }
  /// Returns true if `created` has been explicitly set.
  public var hasCreated: Bool {self._created != nil}
  /// Clears the value of `created`. Subsequent reads from it will return its default value.
  public mutating func clearCreated() {self._created = nil}

  /// The name of the model used for the request. This model name contains
  /// the actual model name used rather than any aliases.
  /// This means the this can be `grok-2-1212` even when the request was
  /// specifying `grok-2-latest`.
  public var model: String = String()

  /// Note supported yet. Included for compatibility reasons.
  public var systemFingerprint: String = String()

  /// The number of tokens consumed by this request.
  public var usage: XaiApi_SamplingUsage {
    get {_usage ?? XaiApi_SamplingUsage()}
    set {_usage = newValue}
  }
  /// Returns true if `usage` has been explicitly set.
  public var hasUsage: Bool {self._usage != nil}
  /// Clears the value of `usage`. Subsequent reads from it will return its default value.
  public mutating func clearUsage() {self._usage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _created: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _usage: XaiApi_SamplingUsage? = nil
}

/// Contains the response generated by the model.
public struct XaiApi_SampleChoice: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicating why the model stopped sampling.
  public var finishReason: XaiApi_FinishReason = .reasonInvalid

  /// The index of this choice in the list of choices. If you set `n > 1` on
  /// your request, you will receive more than one choice in your response.
  public var index: Int32 = 0

  /// The actual text generated by the model.
  public var text: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xai_api"

extension XaiApi_FinishReason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REASON_INVALID\0\u{1}REASON_MAX_LEN\0\u{1}REASON_MAX_CONTEXT\0\u{1}REASON_STOP\0\u{1}REASON_TOOL_CALLS\0\u{1}REASON_TIME_LIMIT\0")
}

extension XaiApi_SampleTextRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SampleTextRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}prompt\0\u{2}\u{2}model\0\u{2}\u{2}logprobs\0\u{3}top_logprobs\0\u{3}max_tokens\0\u{1}n\0\u{3}presence_penalty\0\u{2}\u{2}seed\0\u{1}stop\0\u{3}frequency_penalty\0\u{1}temperature\0\u{3}top_p\0\u{2}\u{2}user\0\u{c}\u{2}\u{1}\u{c}\u{4}\u{1}\u{c}\u{10}\u{1}\u{c}\u{12}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.prompt) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.logprobs) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self._topLogprobs) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self._maxTokens) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._n) }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self._presencePenalty) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self._seed) }()
      case 12: try { try decoder.decodeRepeatedStringField(value: &self.stop) }()
      case 13: try { try decoder.decodeSingularFloatField(value: &self._frequencyPenalty) }()
      case 14: try { try decoder.decodeSingularFloatField(value: &self._temperature) }()
      case 15: try { try decoder.decodeSingularFloatField(value: &self._topP) }()
      case 17: try { try decoder.decodeSingularStringField(value: &self.user) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.prompt.isEmpty {
      try visitor.visitRepeatedStringField(value: self.prompt, fieldNumber: 1)
    }
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 3)
    }
    if self.logprobs != false {
      try visitor.visitSingularBoolField(value: self.logprobs, fieldNumber: 5)
    }
    try { if let v = self._topLogprobs {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._maxTokens {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._n {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._presencePenalty {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._seed {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 11)
    } }()
    if !self.stop.isEmpty {
      try visitor.visitRepeatedStringField(value: self.stop, fieldNumber: 12)
    }
    try { if let v = self._frequencyPenalty {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 13)
    } }()
    try { if let v = self._temperature {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 14)
    } }()
    try { if let v = self._topP {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 15)
    } }()
    if !self.user.isEmpty {
      try visitor.visitSingularStringField(value: self.user, fieldNumber: 17)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_SampleTextRequest, rhs: XaiApi_SampleTextRequest) -> Bool {
    if lhs.prompt != rhs.prompt {return false}
    if lhs.model != rhs.model {return false}
    if lhs._n != rhs._n {return false}
    if lhs._maxTokens != rhs._maxTokens {return false}
    if lhs._seed != rhs._seed {return false}
    if lhs.stop != rhs.stop {return false}
    if lhs._temperature != rhs._temperature {return false}
    if lhs._topP != rhs._topP {return false}
    if lhs._frequencyPenalty != rhs._frequencyPenalty {return false}
    if lhs.logprobs != rhs.logprobs {return false}
    if lhs._presencePenalty != rhs._presencePenalty {return false}
    if lhs._topLogprobs != rhs._topLogprobs {return false}
    if lhs.user != rhs.user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_SampleTextResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SampleTextResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}choices\0\u{2}\u{3}created\0\u{1}model\0\u{3}system_fingerprint\0\u{2}\u{2}usage\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.choices) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._created) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.systemFingerprint) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._usage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.choices.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.choices, fieldNumber: 2)
    }
    try { if let v = self._created {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 6)
    }
    if !self.systemFingerprint.isEmpty {
      try visitor.visitSingularStringField(value: self.systemFingerprint, fieldNumber: 7)
    }
    try { if let v = self._usage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_SampleTextResponse, rhs: XaiApi_SampleTextResponse) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.choices != rhs.choices {return false}
    if lhs._created != rhs._created {return false}
    if lhs.model != rhs.model {return false}
    if lhs.systemFingerprint != rhs.systemFingerprint {return false}
    if lhs._usage != rhs._usage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_SampleChoice: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SampleChoice"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}finish_reason\0\u{1}index\0\u{1}text\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.finishReason) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.index) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.finishReason != .reasonInvalid {
      try visitor.visitSingularEnumField(value: self.finishReason, fieldNumber: 1)
    }
    if self.index != 0 {
      try visitor.visitSingularInt32Field(value: self.index, fieldNumber: 2)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_SampleChoice, rhs: XaiApi_SampleChoice) -> Bool {
    if lhs.finishReason != rhs.finishReason {return false}
    if lhs.index != rhs.index {return false}
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
