// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/sample.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - xai_api.Sample

/// Namespace containing generated types for the "xai_api.Sample" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum XaiApi_Sample: Sendable {
    /// Service descriptor for the "xai_api.Sample" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Sample")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "SampleText" metadata.
        public enum SampleText: Sendable {
            /// Request type for "SampleText".
            public typealias Input = XaiApi_SampleTextRequest
            /// Response type for "SampleText".
            public typealias Output = XaiApi_SampleTextResponse
            /// Descriptor for "SampleText".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Sample"),
                method: "SampleText"
            )
        }
        /// Namespace for "SampleTextStreaming" metadata.
        public enum SampleTextStreaming: Sendable {
            /// Request type for "SampleTextStreaming".
            public typealias Input = XaiApi_SampleTextRequest
            /// Response type for "SampleTextStreaming".
            public typealias Output = XaiApi_SampleTextResponse
            /// Descriptor for "SampleTextStreaming".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Sample"),
                method: "SampleTextStreaming"
            )
        }
        /// Descriptors for all methods in the "xai_api.Sample" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SampleText.descriptor,
            SampleTextStreaming.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "xai_api.Sample" service.
    public static let xaiApi_Sample = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Sample")
}

// MARK: xai_api.Sample (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Sample {
    /// Generated client protocol for the "xai_api.Sample" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for sampling the responses of available language models.
    public protocol ClientProtocol: Sendable {
        /// Call the "SampleText" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get raw sampling of text response from the model inference.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_SampleTextRequest` message.
        ///   - serializer: A serializer for `XaiApi_SampleTextRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_SampleTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func sampleText<Result>(
            request: GRPCCore.ClientRequest<XaiApi_SampleTextRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_SampleTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_SampleTextResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_SampleTextResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SampleTextStreaming" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get streaming raw sampling of text response from the model inference.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_SampleTextRequest` message.
        ///   - serializer: A serializer for `XaiApi_SampleTextRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_SampleTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func sampleTextStreaming<Result>(
            request: GRPCCore.ClientRequest<XaiApi_SampleTextRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_SampleTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_SampleTextResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<XaiApi_SampleTextResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "xai_api.Sample" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for sampling the responses of available language models.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SampleText" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get raw sampling of text response from the model inference.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_SampleTextRequest` message.
        ///   - serializer: A serializer for `XaiApi_SampleTextRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_SampleTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func sampleText<Result>(
            request: GRPCCore.ClientRequest<XaiApi_SampleTextRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_SampleTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_SampleTextResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_SampleTextResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_Sample.Method.SampleText.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SampleTextStreaming" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get streaming raw sampling of text response from the model inference.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_SampleTextRequest` message.
        ///   - serializer: A serializer for `XaiApi_SampleTextRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_SampleTextResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func sampleTextStreaming<Result>(
            request: GRPCCore.ClientRequest<XaiApi_SampleTextRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_SampleTextRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_SampleTextResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<XaiApi_SampleTextResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: XaiApi_Sample.Method.SampleTextStreaming.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Sample.ClientProtocol {
    /// Call the "SampleText" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get raw sampling of text response from the model inference.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_SampleTextRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sampleText<Result>(
        request: GRPCCore.ClientRequest<XaiApi_SampleTextRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_SampleTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.sampleText(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_SampleTextRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_SampleTextResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SampleTextStreaming" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get streaming raw sampling of text response from the model inference.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_SampleTextRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sampleTextStreaming<Result>(
        request: GRPCCore.ClientRequest<XaiApi_SampleTextRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<XaiApi_SampleTextResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.sampleTextStreaming(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_SampleTextRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_SampleTextResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Sample.ClientProtocol {
    /// Call the "SampleText" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get raw sampling of text response from the model inference.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sampleText<Result>(
        _ message: XaiApi_SampleTextRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_SampleTextResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_SampleTextRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sampleText(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SampleTextStreaming" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get streaming raw sampling of text response from the model inference.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sampleTextStreaming<Result>(
        _ message: XaiApi_SampleTextRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<XaiApi_SampleTextResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_SampleTextRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sampleTextStreaming(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}