// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/video.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Aspect ratio for video generation.
public enum XaiApi_VideoAspectRatio: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Invalid/unspecified aspect ratio - defaults to 16:9.
  case unspecified // = 0

  /// 1:1 aspect ratio (square).
  case videoAspectRatio11 // = 1

  /// 16:9 aspect ratio (wide landscape).
  case videoAspectRatio169 // = 2

  /// 9:16 aspect ratio (tall portrait).
  case videoAspectRatio916 // = 3

  /// 4:3 aspect ratio (standard landscape).
  case videoAspectRatio43 // = 4

  /// 3:4 aspect ratio (standard portrait).
  case videoAspectRatio34 // = 5

  /// 3:2 aspect ratio (photo landscape).
  case videoAspectRatio32 // = 6

  /// 2:3 aspect ratio (photo portrait).
  case videoAspectRatio23 // = 7
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .videoAspectRatio11
    case 2: self = .videoAspectRatio169
    case 3: self = .videoAspectRatio916
    case 4: self = .videoAspectRatio43
    case 5: self = .videoAspectRatio34
    case 6: self = .videoAspectRatio32
    case 7: self = .videoAspectRatio23
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .videoAspectRatio11: return 1
    case .videoAspectRatio169: return 2
    case .videoAspectRatio916: return 3
    case .videoAspectRatio43: return 4
    case .videoAspectRatio34: return 5
    case .videoAspectRatio32: return 6
    case .videoAspectRatio23: return 7
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_VideoAspectRatio] = [
    .unspecified,
    .videoAspectRatio11,
    .videoAspectRatio169,
    .videoAspectRatio916,
    .videoAspectRatio43,
    .videoAspectRatio34,
    .videoAspectRatio32,
    .videoAspectRatio23,
  ]

}

/// Resolution for video generation.
public enum XaiApi_VideoResolution: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// Invalid/unspecified resolution - defaults to 480p.
  case unspecified // = 0

  /// 480p resolution.
  /// Dimensions vary by aspect ratio
  case videoResolution480P // = 1

  /// 720p resolution.
  /// Dimensions vary by aspect ratio
  case videoResolution720P // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .videoResolution480P
    case 2: self = .videoResolution720P
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .videoResolution480P: return 1
    case .videoResolution720P: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [XaiApi_VideoResolution] = [
    .unspecified,
    .videoResolution480P,
    .videoResolution720P,
  ]

}

/// Specifies a video by URL for video editing.
public struct XaiApi_VideoUrlContent: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Either a URL of the video (e.g., a public URL) or a base64-encoded video
  /// as a data URL (e.g., "data:video/mp4;base64,...").
  public var url: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Output destination for generated video.
public struct XaiApi_VideoOutput: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Signed URL to upload the generated video via HTTP PUT.
  public var uploadURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Request message for generating a video.
public struct XaiApi_GenerateVideoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Input prompt to generate a video from.
  public var prompt: String = String()

  /// Optional input image for image-to-video generation.
  /// If provided, generates video with this image as the first frame.
  /// If omitted, generates text-to-video.
  /// Supports the same formats as image generation: URL or base64-encoded image.
  public var image: XaiApi_ImageUrlContent {
    get {_image ?? XaiApi_ImageUrlContent()}
    set {_image = newValue}
  }
  /// Returns true if `image` has been explicitly set.
  public var hasImage: Bool {self._image != nil}
  /// Clears the value of `image`. Subsequent reads from it will return its default value.
  public mutating func clearImage() {self._image = nil}

  /// Name or alias of the video generation model to be used.
  public var model: String = String()

  /// Duration of the video to be generated in seconds (1-15 seconds).
  public var duration: Int32 {
    get {_duration ?? 0}
    set {_duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {self._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {self._duration = nil}

  /// Optional input video for video editing.
  /// If provided, the video will be edited based on the prompt.
  /// Supports URL or base64-encoded video data.
  public var video: XaiApi_VideoUrlContent {
    get {_video ?? XaiApi_VideoUrlContent()}
    set {_video = newValue}
  }
  /// Returns true if `video` has been explicitly set.
  public var hasVideo: Bool {self._video != nil}
  /// Clears the value of `video`. Subsequent reads from it will return its default value.
  public mutating func clearVideo() {self._video = nil}

  /// Optional aspect ratio for video generation.
  /// Defaults to 16:9 if not specified.
  public var aspectRatio: XaiApi_VideoAspectRatio {
    get {_aspectRatio ?? .unspecified}
    set {_aspectRatio = newValue}
  }
  /// Returns true if `aspectRatio` has been explicitly set.
  public var hasAspectRatio: Bool {self._aspectRatio != nil}
  /// Clears the value of `aspectRatio`. Subsequent reads from it will return its default value.
  public mutating func clearAspectRatio() {self._aspectRatio = nil}

  /// Optional resolution for video generation.
  /// Defaults to 480p if not specified.
  public var resolution: XaiApi_VideoResolution {
    get {_resolution ?? .unspecified}
    set {_resolution = newValue}
  }
  /// Returns true if `resolution` has been explicitly set.
  public var hasResolution: Bool {self._resolution != nil}
  /// Clears the value of `resolution`. Subsequent reads from it will return its default value.
  public mutating func clearResolution() {self._resolution = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _image: XaiApi_ImageUrlContent? = nil
  fileprivate var _duration: Int32? = nil
  fileprivate var _video: XaiApi_VideoUrlContent? = nil
  fileprivate var _aspectRatio: XaiApi_VideoAspectRatio? = nil
  fileprivate var _resolution: XaiApi_VideoResolution? = nil
}

/// Request for retrieving deferred video generation results.
public struct XaiApi_GetDeferredVideoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID of the request to get.
  public var requestID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The response from the video generation models containing the generated video.
public struct XaiApi_VideoResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The generated video.
  public var video: XaiApi_GeneratedVideo {
    get {_video ?? XaiApi_GeneratedVideo()}
    set {_video = newValue}
  }
  /// Returns true if `video` has been explicitly set.
  public var hasVideo: Bool {self._video != nil}
  /// Clears the value of `video`. Subsequent reads from it will return its default value.
  public mutating func clearVideo() {self._video = nil}

  /// The model used to generate the video (ignoring aliases).
  public var model: String = String()

  /// The usage of the request.
  public var usage: XaiApi_SamplingUsage {
    get {_usage ?? XaiApi_SamplingUsage()}
    set {_usage = newValue}
  }
  /// Returns true if `usage` has been explicitly set.
  public var hasUsage: Bool {self._usage != nil}
  /// Clears the value of `usage`. Subsequent reads from it will return its default value.
  public mutating func clearUsage() {self._usage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _video: XaiApi_GeneratedVideo? = nil
  fileprivate var _usage: XaiApi_SamplingUsage? = nil
}

/// Contains all data related to a generated video.
public struct XaiApi_GeneratedVideo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// A url that points to the generated video.
  public var url: String = String()

  /// Duration of the generated video in seconds.
  public var duration: Int32 = 0

  /// Whether the video generated by the model respects moderation rules.
  /// The field will be true if the video respects moderation rules. Otherwise
  /// the field will be false and the video url field will be empty.
  public var respectModeration: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Response from GetDeferredVideo, including the response if the video
/// generation request has been processed without error.
public struct XaiApi_GetDeferredVideoResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Current status of the request.
  public var status: XaiApi_DeferredStatus = .invalidDeferredStatus

  /// Response. Only present if `status=DONE`
  public var response: XaiApi_VideoResponse {
    get {_response ?? XaiApi_VideoResponse()}
    set {_response = newValue}
  }
  /// Returns true if `response` has been explicitly set.
  public var hasResponse: Bool {self._response != nil}
  /// Clears the value of `response`. Subsequent reads from it will return its default value.
  public mutating func clearResponse() {self._response = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _response: XaiApi_VideoResponse? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "xai_api"

extension XaiApi_VideoAspectRatio: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VIDEO_ASPECT_RATIO_UNSPECIFIED\0\u{1}VIDEO_ASPECT_RATIO_1_1\0\u{1}VIDEO_ASPECT_RATIO_16_9\0\u{1}VIDEO_ASPECT_RATIO_9_16\0\u{1}VIDEO_ASPECT_RATIO_4_3\0\u{1}VIDEO_ASPECT_RATIO_3_4\0\u{1}VIDEO_ASPECT_RATIO_3_2\0\u{1}VIDEO_ASPECT_RATIO_2_3\0")
}

extension XaiApi_VideoResolution: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VIDEO_RESOLUTION_UNSPECIFIED\0\u{1}VIDEO_RESOLUTION_480P\0\u{1}VIDEO_RESOLUTION_720P\0")
}

extension XaiApi_VideoUrlContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoUrlContent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.url) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_VideoUrlContent, rhs: XaiApi_VideoUrlContent) -> Bool {
    if lhs.url != rhs.url {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_VideoOutput: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoOutput"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}upload_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.uploadURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.uploadURL.isEmpty {
      try visitor.visitSingularStringField(value: self.uploadURL, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_VideoOutput, rhs: XaiApi_VideoOutput) -> Bool {
    if lhs.uploadURL != rhs.uploadURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_GenerateVideoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GenerateVideoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}prompt\0\u{1}image\0\u{1}model\0\u{1}duration\0\u{2}\u{2}video\0\u{3}aspect_ratio\0\u{1}resolution\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.prompt) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._image) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._duration) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._video) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self._aspectRatio) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self._resolution) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.prompt.isEmpty {
      try visitor.visitSingularStringField(value: self.prompt, fieldNumber: 1)
    }
    try { if let v = self._image {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 3)
    }
    try { if let v = self._duration {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._video {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._aspectRatio {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._resolution {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 8)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GenerateVideoRequest, rhs: XaiApi_GenerateVideoRequest) -> Bool {
    if lhs.prompt != rhs.prompt {return false}
    if lhs._image != rhs._image {return false}
    if lhs.model != rhs.model {return false}
    if lhs._duration != rhs._duration {return false}
    if lhs._video != rhs._video {return false}
    if lhs._aspectRatio != rhs._aspectRatio {return false}
    if lhs._resolution != rhs._resolution {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_GetDeferredVideoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetDeferredVideoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GetDeferredVideoRequest, rhs: XaiApi_GetDeferredVideoRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_VideoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".VideoResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}video\0\u{1}model\0\u{1}usage\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._video) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._usage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._video {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 2)
    }
    try { if let v = self._usage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_VideoResponse, rhs: XaiApi_VideoResponse) -> Bool {
    if lhs._video != rhs._video {return false}
    if lhs.model != rhs.model {return false}
    if lhs._usage != rhs._usage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_GeneratedVideo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GeneratedVideo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}url\0\u{2}\u{3}duration\0\u{3}respect_moderation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.duration) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.respectModeration) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 1)
    }
    if self.duration != 0 {
      try visitor.visitSingularInt32Field(value: self.duration, fieldNumber: 4)
    }
    if self.respectModeration != false {
      try visitor.visitSingularBoolField(value: self.respectModeration, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GeneratedVideo, rhs: XaiApi_GeneratedVideo) -> Bool {
    if lhs.url != rhs.url {return false}
    if lhs.duration != rhs.duration {return false}
    if lhs.respectModeration != rhs.respectModeration {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension XaiApi_GetDeferredVideoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetDeferredVideoResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{1}response\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._response) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.status != .invalidDeferredStatus {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    try { if let v = self._response {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: XaiApi_GetDeferredVideoResponse, rhs: XaiApi_GetDeferredVideoResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs._response != rhs._response {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
