// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: xai/api/v1/video.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - xai_api.Video

/// Namespace containing generated types for the "xai_api.Video" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum XaiApi_Video: Sendable {
    /// Service descriptor for the "xai_api.Video" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Video")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GenerateVideo" metadata.
        public enum GenerateVideo: Sendable {
            /// Request type for "GenerateVideo".
            public typealias Input = XaiApi_GenerateVideoRequest
            /// Response type for "GenerateVideo".
            public typealias Output = XaiApi_StartDeferredResponse
            /// Descriptor for "GenerateVideo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Video"),
                method: "GenerateVideo",
                type: .unary
            )
        }
        /// Namespace for "ExtendVideo" metadata.
        public enum ExtendVideo: Sendable {
            /// Request type for "ExtendVideo".
            public typealias Input = XaiApi_ExtendVideoRequest
            /// Response type for "ExtendVideo".
            public typealias Output = XaiApi_StartDeferredResponse
            /// Descriptor for "ExtendVideo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Video"),
                method: "ExtendVideo",
                type: .unary
            )
        }
        /// Namespace for "GetDeferredVideo" metadata.
        public enum GetDeferredVideo: Sendable {
            /// Request type for "GetDeferredVideo".
            public typealias Input = XaiApi_GetDeferredVideoRequest
            /// Response type for "GetDeferredVideo".
            public typealias Output = XaiApi_GetDeferredVideoResponse
            /// Descriptor for "GetDeferredVideo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Video"),
                method: "GetDeferredVideo",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "xai_api.Video" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GenerateVideo.descriptor,
            ExtendVideo.descriptor,
            GetDeferredVideo.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "xai_api.Video" service.
    public static let xaiApi_Video = GRPCCore.ServiceDescriptor(fullyQualifiedService: "xai_api.Video")
}

// MARK: xai_api.Video (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Video {
    /// Generated client protocol for the "xai_api.Video" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for interaction with video generation models.
    public protocol ClientProtocol: Sendable {
        /// Call the "GenerateVideo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create a video based on a text prompt and optionally an image.
        /// > If an image is provided, generates video with the image as the first frame
        /// > (image-to-video). If no image is provided, generates video from text only
        /// > (text-to-video).
        /// > 
        /// > This is an asynchronous operation. The method returns immediately with a
        /// > request_id that can be used to poll for the result using GetDeferredVideo.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GenerateVideoRequest` message.
        ///   - serializer: A serializer for `XaiApi_GenerateVideoRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_StartDeferredResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func generateVideo<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GenerateVideoRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GenerateVideoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_StartDeferredResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_StartDeferredResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ExtendVideo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Extend an existing video by generating continuation content.
        /// > 
        /// > This is an asynchronous operation. The method returns immediately with a
        /// > request_id that can be used to poll for the result using GetDeferredVideo.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_ExtendVideoRequest` message.
        ///   - serializer: A serializer for `XaiApi_ExtendVideoRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_StartDeferredResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func extendVideo<Result>(
            request: GRPCCore.ClientRequest<XaiApi_ExtendVideoRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_ExtendVideoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_StartDeferredResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_StartDeferredResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetDeferredVideo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Gets the result of a video generation started by calling `GenerateVideo` or
        /// > `ExtendVideo`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GetDeferredVideoRequest` message.
        ///   - serializer: A serializer for `XaiApi_GetDeferredVideoRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_GetDeferredVideoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getDeferredVideo<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GetDeferredVideoRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GetDeferredVideoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_GetDeferredVideoResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_GetDeferredVideoResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "xai_api.Video" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > An API service for interaction with video generation models.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GenerateVideo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Create a video based on a text prompt and optionally an image.
        /// > If an image is provided, generates video with the image as the first frame
        /// > (image-to-video). If no image is provided, generates video from text only
        /// > (text-to-video).
        /// > 
        /// > This is an asynchronous operation. The method returns immediately with a
        /// > request_id that can be used to poll for the result using GetDeferredVideo.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GenerateVideoRequest` message.
        ///   - serializer: A serializer for `XaiApi_GenerateVideoRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_StartDeferredResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func generateVideo<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GenerateVideoRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GenerateVideoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_StartDeferredResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_StartDeferredResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_Video.Method.GenerateVideo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ExtendVideo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Extend an existing video by generating continuation content.
        /// > 
        /// > This is an asynchronous operation. The method returns immediately with a
        /// > request_id that can be used to poll for the result using GetDeferredVideo.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_ExtendVideoRequest` message.
        ///   - serializer: A serializer for `XaiApi_ExtendVideoRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_StartDeferredResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func extendVideo<Result>(
            request: GRPCCore.ClientRequest<XaiApi_ExtendVideoRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_ExtendVideoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_StartDeferredResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_StartDeferredResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_Video.Method.ExtendVideo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetDeferredVideo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Gets the result of a video generation started by calling `GenerateVideo` or
        /// > `ExtendVideo`.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `XaiApi_GetDeferredVideoRequest` message.
        ///   - serializer: A serializer for `XaiApi_GetDeferredVideoRequest` messages.
        ///   - deserializer: A deserializer for `XaiApi_GetDeferredVideoResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getDeferredVideo<Result>(
            request: GRPCCore.ClientRequest<XaiApi_GetDeferredVideoRequest>,
            serializer: some GRPCCore.MessageSerializer<XaiApi_GetDeferredVideoRequest>,
            deserializer: some GRPCCore.MessageDeserializer<XaiApi_GetDeferredVideoResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_GetDeferredVideoResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: XaiApi_Video.Method.GetDeferredVideo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Video.ClientProtocol {
    /// Call the "GenerateVideo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create a video based on a text prompt and optionally an image.
    /// > If an image is provided, generates video with the image as the first frame
    /// > (image-to-video). If no image is provided, generates video from text only
    /// > (text-to-video).
    /// > 
    /// > This is an asynchronous operation. The method returns immediately with a
    /// > request_id that can be used to poll for the result using GetDeferredVideo.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_GenerateVideoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateVideo<Result>(
        request: GRPCCore.ClientRequest<XaiApi_GenerateVideoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_StartDeferredResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.generateVideo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_GenerateVideoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_StartDeferredResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ExtendVideo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Extend an existing video by generating continuation content.
    /// > 
    /// > This is an asynchronous operation. The method returns immediately with a
    /// > request_id that can be used to poll for the result using GetDeferredVideo.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_ExtendVideoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func extendVideo<Result>(
        request: GRPCCore.ClientRequest<XaiApi_ExtendVideoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_StartDeferredResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.extendVideo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_ExtendVideoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_StartDeferredResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetDeferredVideo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Gets the result of a video generation started by calling `GenerateVideo` or
    /// > `ExtendVideo`.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `XaiApi_GetDeferredVideoRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getDeferredVideo<Result>(
        request: GRPCCore.ClientRequest<XaiApi_GetDeferredVideoRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_GetDeferredVideoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getDeferredVideo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<XaiApi_GetDeferredVideoRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<XaiApi_GetDeferredVideoResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension XaiApi_Video.ClientProtocol {
    /// Call the "GenerateVideo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Create a video based on a text prompt and optionally an image.
    /// > If an image is provided, generates video with the image as the first frame
    /// > (image-to-video). If no image is provided, generates video from text only
    /// > (text-to-video).
    /// > 
    /// > This is an asynchronous operation. The method returns immediately with a
    /// > request_id that can be used to poll for the result using GetDeferredVideo.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func generateVideo<Result>(
        _ message: XaiApi_GenerateVideoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_StartDeferredResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_GenerateVideoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.generateVideo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ExtendVideo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Extend an existing video by generating continuation content.
    /// > 
    /// > This is an asynchronous operation. The method returns immediately with a
    /// > request_id that can be used to poll for the result using GetDeferredVideo.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func extendVideo<Result>(
        _ message: XaiApi_ExtendVideoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_StartDeferredResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_ExtendVideoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.extendVideo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetDeferredVideo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Gets the result of a video generation started by calling `GenerateVideo` or
    /// > `ExtendVideo`.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getDeferredVideo<Result>(
        _ message: XaiApi_GetDeferredVideoRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<XaiApi_GetDeferredVideoResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<XaiApi_GetDeferredVideoRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getDeferredVideo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}