// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: xai/management_api/v1/billing.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - prod_mc_billing.UISvc

/// Namespace containing generated types for the "prod_mc_billing.UISvc" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum ProdMcBilling_UISvc: Sendable {
    /// Service descriptor for the "prod_mc_billing.UISvc" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "SetBillingInfo" metadata.
        public enum SetBillingInfo: Sendable {
            /// Request type for "SetBillingInfo".
            public typealias Input = ProdMcBilling_SetBillingInfoReq
            /// Response type for "SetBillingInfo".
            public typealias Output = ProdMcBilling_SetBillingInfoResp
            /// Descriptor for "SetBillingInfo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "SetBillingInfo",
                type: .unary
            )
        }
        /// Namespace for "GetBillingInfo" metadata.
        public enum GetBillingInfo: Sendable {
            /// Request type for "GetBillingInfo".
            public typealias Input = ProdMcBilling_GetBillingInfoReq
            /// Response type for "GetBillingInfo".
            public typealias Output = ProdMcBilling_GetBillingInfoResp
            /// Descriptor for "GetBillingInfo".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "GetBillingInfo",
                type: .unary
            )
        }
        /// Namespace for "ListPaymentMethods" metadata.
        public enum ListPaymentMethods: Sendable {
            /// Request type for "ListPaymentMethods".
            public typealias Input = ProdMcBilling_ListPaymentMethodsReq
            /// Response type for "ListPaymentMethods".
            public typealias Output = ProdMcBilling_ListPaymentMethodsResp
            /// Descriptor for "ListPaymentMethods".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "ListPaymentMethods",
                type: .unary
            )
        }
        /// Namespace for "SetDefaultPaymentMethod" metadata.
        public enum SetDefaultPaymentMethod: Sendable {
            /// Request type for "SetDefaultPaymentMethod".
            public typealias Input = ProdMcBilling_SetDefaultPaymentMethodReq
            /// Response type for "SetDefaultPaymentMethod".
            public typealias Output = ProdMcBilling_SetDefaultPaymentMethodResp
            /// Descriptor for "SetDefaultPaymentMethod".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "SetDefaultPaymentMethod",
                type: .unary
            )
        }
        /// Namespace for "GetAmountToPay" metadata.
        public enum GetAmountToPay: Sendable {
            /// Request type for "GetAmountToPay".
            public typealias Input = ProdMcBilling_GetAmountToPayReq
            /// Response type for "GetAmountToPay".
            public typealias Output = ProdMcBilling_GetAmountToPayResp
            /// Descriptor for "GetAmountToPay".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "GetAmountToPay",
                type: .unary
            )
        }
        /// Namespace for "AnalyzeBillingItems" metadata.
        public enum AnalyzeBillingItems: Sendable {
            /// Request type for "AnalyzeBillingItems".
            public typealias Input = ProdMcBilling_AnalyzeBillingItemsRequest
            /// Response type for "AnalyzeBillingItems".
            public typealias Output = Prod_ClickhouseAnalytics_AnalyticsResponse
            /// Descriptor for "AnalyzeBillingItems".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "AnalyzeBillingItems",
                type: .unary
            )
        }
        /// Namespace for "ListInvoices" metadata.
        public enum ListInvoices: Sendable {
            /// Request type for "ListInvoices".
            public typealias Input = ProdMcBilling_ListInvoicesReq
            /// Response type for "ListInvoices".
            public typealias Output = ProdMcBilling_ListInvoicesResp
            /// Descriptor for "ListInvoices".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "ListInvoices",
                type: .unary
            )
        }
        /// Namespace for "ListPrepaidBalanceChanges" metadata.
        public enum ListPrepaidBalanceChanges: Sendable {
            /// Request type for "ListPrepaidBalanceChanges".
            public typealias Input = ProdMcBilling_ListPrepaidBalanceChangesReq
            /// Response type for "ListPrepaidBalanceChanges".
            public typealias Output = ProdMcBilling_ListPrepaidBalanceChangesResp
            /// Descriptor for "ListPrepaidBalanceChanges".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "ListPrepaidBalanceChanges",
                type: .unary
            )
        }
        /// Namespace for "TopUpOrGetExistingPendingChange" metadata.
        public enum TopUpOrGetExistingPendingChange: Sendable {
            /// Request type for "TopUpOrGetExistingPendingChange".
            public typealias Input = ProdMcBilling_TopUpOrGetExistingPendingChangeReq
            /// Response type for "TopUpOrGetExistingPendingChange".
            public typealias Output = ProdMcBilling_TopUpOrGetExistingPendingChangeResp
            /// Descriptor for "TopUpOrGetExistingPendingChange".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "TopUpOrGetExistingPendingChange",
                type: .unary
            )
        }
        /// Namespace for "GetSpendingLimits" metadata.
        public enum GetSpendingLimits: Sendable {
            /// Request type for "GetSpendingLimits".
            public typealias Input = ProdMcBilling_GetSpendingLimitsReq
            /// Response type for "GetSpendingLimits".
            public typealias Output = ProdMcBilling_GetSpendingLimitsResp
            /// Descriptor for "GetSpendingLimits".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "GetSpendingLimits",
                type: .unary
            )
        }
        /// Namespace for "SetSoftSpendingLimit" metadata.
        public enum SetSoftSpendingLimit: Sendable {
            /// Request type for "SetSoftSpendingLimit".
            public typealias Input = ProdMcBilling_SetSoftSpendingLimitReq
            /// Response type for "SetSoftSpendingLimit".
            public typealias Output = ProdMcBilling_SetSoftSpendingLimitResp
            /// Descriptor for "SetSoftSpendingLimit".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc"),
                method: "SetSoftSpendingLimit",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "prod_mc_billing.UISvc" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SetBillingInfo.descriptor,
            GetBillingInfo.descriptor,
            ListPaymentMethods.descriptor,
            SetDefaultPaymentMethod.descriptor,
            GetAmountToPay.descriptor,
            AnalyzeBillingItems.descriptor,
            ListInvoices.descriptor,
            ListPrepaidBalanceChanges.descriptor,
            TopUpOrGetExistingPendingChange.descriptor,
            GetSpendingLimits.descriptor,
            SetSoftSpendingLimit.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "prod_mc_billing.UISvc" service.
    public static let prodMcBilling_UISvc = GRPCCore.ServiceDescriptor(fullyQualifiedService: "prod_mc_billing.UISvc")
}

// MARK: prod_mc_billing.UISvc (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ProdMcBilling_UISvc {
    /// Generated client protocol for the "prod_mc_billing.UISvc" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > gRPC API service to interact with the xAI billing system.
    public protocol ClientProtocol: Sendable {
        /// Call the "SetBillingInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Set billing information of a team.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_SetBillingInfoReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_SetBillingInfoReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_SetBillingInfoResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setBillingInfo<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_SetBillingInfoReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_SetBillingInfoReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_SetBillingInfoResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetBillingInfoResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetBillingInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get billing information of the team with given team ID.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_GetBillingInfoReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_GetBillingInfoReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_GetBillingInfoResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getBillingInfo<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_GetBillingInfoReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_GetBillingInfoReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_GetBillingInfoResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetBillingInfoResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListPaymentMethods" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List payment methods of a team. You can add or delete the payment methods on https://console.x.ai.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_ListPaymentMethodsReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_ListPaymentMethodsReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_ListPaymentMethodsResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listPaymentMethods<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_ListPaymentMethodsReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_ListPaymentMethodsReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_ListPaymentMethodsResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListPaymentMethodsResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetDefaultPaymentMethod" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Set default payment method to an existing payment method on file.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_SetDefaultPaymentMethodReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_SetDefaultPaymentMethodReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_SetDefaultPaymentMethodResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setDefaultPaymentMethod<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_SetDefaultPaymentMethodReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_SetDefaultPaymentMethodReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_SetDefaultPaymentMethodResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetDefaultPaymentMethodResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetAmountToPay" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Preview the amount to pay for postpaid usage in the current billing period.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_GetAmountToPayReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_GetAmountToPayReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_GetAmountToPayResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getAmountToPay<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_GetAmountToPayReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_GetAmountToPayReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_GetAmountToPayResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetAmountToPayResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "AnalyzeBillingItems" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get historical usage of the API over a time period, aggregated by fields.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_AnalyzeBillingItemsRequest` message.
        ///   - serializer: A serializer for `ProdMcBilling_AnalyzeBillingItemsRequest` messages.
        ///   - deserializer: A deserializer for `Prod_ClickhouseAnalytics_AnalyticsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func analyzeBillingItems<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_AnalyzeBillingItemsRequest>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_AnalyzeBillingItemsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Prod_ClickhouseAnalytics_AnalyticsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Prod_ClickhouseAnalytics_AnalyticsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListInvoices" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List invoices that belong to a team.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_ListInvoicesReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_ListInvoicesReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_ListInvoicesResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listInvoices<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_ListInvoicesReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_ListInvoicesReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_ListInvoicesResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListInvoicesResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListPrepaidBalanceChanges" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List the prepaid credit balance and balance changes of a team.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_ListPrepaidBalanceChangesReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_ListPrepaidBalanceChangesReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_ListPrepaidBalanceChangesResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listPrepaidBalanceChanges<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_ListPrepaidBalanceChangesReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_ListPrepaidBalanceChangesReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_ListPrepaidBalanceChangesResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListPrepaidBalanceChangesResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "TopUpOrGetExistingPendingChange" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Top up prepaid credit using the default payment method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_TopUpOrGetExistingPendingChangeReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_TopUpOrGetExistingPendingChangeReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_TopUpOrGetExistingPendingChangeResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func topUpOrGetExistingPendingChange<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_TopUpOrGetExistingPendingChangeReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_TopUpOrGetExistingPendingChangeReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_TopUpOrGetExistingPendingChangeResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_TopUpOrGetExistingPendingChangeResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetSpendingLimits" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get the postpaid monthly spending limits. The API will stop functioning once the team has consumed all of the
        /// > prepaid credits, and the postpaid usage amount has reached the user-set soft spending limit.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_GetSpendingLimitsReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_GetSpendingLimitsReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_GetSpendingLimitsResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getSpendingLimits<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_GetSpendingLimitsReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_GetSpendingLimitsReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_GetSpendingLimitsResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetSpendingLimitsResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SetSoftSpendingLimit" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Set the postpaid monthly spending limit of a team. This can be used to restrict the maximum amount of postpaid API
        /// > usage. Note this will not limit the amount of prepaid credit usage, and prepaid credits will always be consumed
        /// > before accruing postpaid usage. To use only prepaid credits, you can set this limit to 0.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_SetSoftSpendingLimitReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_SetSoftSpendingLimitReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_SetSoftSpendingLimitResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func setSoftSpendingLimit<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_SetSoftSpendingLimitReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_SetSoftSpendingLimitReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_SetSoftSpendingLimitResp>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetSoftSpendingLimitResp>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "prod_mc_billing.UISvc" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > gRPC API service to interact with the xAI billing system.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SetBillingInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Set billing information of a team.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_SetBillingInfoReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_SetBillingInfoReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_SetBillingInfoResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setBillingInfo<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_SetBillingInfoReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_SetBillingInfoReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_SetBillingInfoResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetBillingInfoResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.SetBillingInfo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetBillingInfo" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get billing information of the team with given team ID.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_GetBillingInfoReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_GetBillingInfoReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_GetBillingInfoResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getBillingInfo<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_GetBillingInfoReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_GetBillingInfoReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_GetBillingInfoResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetBillingInfoResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.GetBillingInfo.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListPaymentMethods" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List payment methods of a team. You can add or delete the payment methods on https://console.x.ai.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_ListPaymentMethodsReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_ListPaymentMethodsReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_ListPaymentMethodsResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listPaymentMethods<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_ListPaymentMethodsReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_ListPaymentMethodsReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_ListPaymentMethodsResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListPaymentMethodsResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.ListPaymentMethods.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetDefaultPaymentMethod" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Set default payment method to an existing payment method on file.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_SetDefaultPaymentMethodReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_SetDefaultPaymentMethodReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_SetDefaultPaymentMethodResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setDefaultPaymentMethod<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_SetDefaultPaymentMethodReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_SetDefaultPaymentMethodReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_SetDefaultPaymentMethodResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetDefaultPaymentMethodResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.SetDefaultPaymentMethod.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetAmountToPay" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Preview the amount to pay for postpaid usage in the current billing period.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_GetAmountToPayReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_GetAmountToPayReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_GetAmountToPayResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getAmountToPay<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_GetAmountToPayReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_GetAmountToPayReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_GetAmountToPayResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetAmountToPayResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.GetAmountToPay.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "AnalyzeBillingItems" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get historical usage of the API over a time period, aggregated by fields.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_AnalyzeBillingItemsRequest` message.
        ///   - serializer: A serializer for `ProdMcBilling_AnalyzeBillingItemsRequest` messages.
        ///   - deserializer: A deserializer for `Prod_ClickhouseAnalytics_AnalyticsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func analyzeBillingItems<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_AnalyzeBillingItemsRequest>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_AnalyzeBillingItemsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Prod_ClickhouseAnalytics_AnalyticsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Prod_ClickhouseAnalytics_AnalyticsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.AnalyzeBillingItems.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListInvoices" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List invoices that belong to a team.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_ListInvoicesReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_ListInvoicesReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_ListInvoicesResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listInvoices<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_ListInvoicesReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_ListInvoicesReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_ListInvoicesResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListInvoicesResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.ListInvoices.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListPrepaidBalanceChanges" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > List the prepaid credit balance and balance changes of a team.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_ListPrepaidBalanceChangesReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_ListPrepaidBalanceChangesReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_ListPrepaidBalanceChangesResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listPrepaidBalanceChanges<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_ListPrepaidBalanceChangesReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_ListPrepaidBalanceChangesReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_ListPrepaidBalanceChangesResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListPrepaidBalanceChangesResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.ListPrepaidBalanceChanges.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "TopUpOrGetExistingPendingChange" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Top up prepaid credit using the default payment method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_TopUpOrGetExistingPendingChangeReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_TopUpOrGetExistingPendingChangeReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_TopUpOrGetExistingPendingChangeResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func topUpOrGetExistingPendingChange<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_TopUpOrGetExistingPendingChangeReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_TopUpOrGetExistingPendingChangeReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_TopUpOrGetExistingPendingChangeResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_TopUpOrGetExistingPendingChangeResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.TopUpOrGetExistingPendingChange.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetSpendingLimits" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Get the postpaid monthly spending limits. The API will stop functioning once the team has consumed all of the
        /// > prepaid credits, and the postpaid usage amount has reached the user-set soft spending limit.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_GetSpendingLimitsReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_GetSpendingLimitsReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_GetSpendingLimitsResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getSpendingLimits<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_GetSpendingLimitsReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_GetSpendingLimitsReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_GetSpendingLimitsResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetSpendingLimitsResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.GetSpendingLimits.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SetSoftSpendingLimit" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Set the postpaid monthly spending limit of a team. This can be used to restrict the maximum amount of postpaid API
        /// > usage. Note this will not limit the amount of prepaid credit usage, and prepaid credits will always be consumed
        /// > before accruing postpaid usage. To use only prepaid credits, you can set this limit to 0.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ProdMcBilling_SetSoftSpendingLimitReq` message.
        ///   - serializer: A serializer for `ProdMcBilling_SetSoftSpendingLimitReq` messages.
        ///   - deserializer: A deserializer for `ProdMcBilling_SetSoftSpendingLimitResp` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func setSoftSpendingLimit<Result>(
            request: GRPCCore.ClientRequest<ProdMcBilling_SetSoftSpendingLimitReq>,
            serializer: some GRPCCore.MessageSerializer<ProdMcBilling_SetSoftSpendingLimitReq>,
            deserializer: some GRPCCore.MessageDeserializer<ProdMcBilling_SetSoftSpendingLimitResp>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetSoftSpendingLimitResp>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: ProdMcBilling_UISvc.Method.SetSoftSpendingLimit.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ProdMcBilling_UISvc.ClientProtocol {
    /// Call the "SetBillingInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Set billing information of a team.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_SetBillingInfoReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setBillingInfo<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_SetBillingInfoReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetBillingInfoResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setBillingInfo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_SetBillingInfoReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_SetBillingInfoResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetBillingInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get billing information of the team with given team ID.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_GetBillingInfoReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBillingInfo<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_GetBillingInfoReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetBillingInfoResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getBillingInfo(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_GetBillingInfoReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_GetBillingInfoResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListPaymentMethods" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List payment methods of a team. You can add or delete the payment methods on https://console.x.ai.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_ListPaymentMethodsReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listPaymentMethods<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_ListPaymentMethodsReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListPaymentMethodsResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listPaymentMethods(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_ListPaymentMethodsReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_ListPaymentMethodsResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetDefaultPaymentMethod" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Set default payment method to an existing payment method on file.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_SetDefaultPaymentMethodReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setDefaultPaymentMethod<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_SetDefaultPaymentMethodReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetDefaultPaymentMethodResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setDefaultPaymentMethod(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_SetDefaultPaymentMethodReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_SetDefaultPaymentMethodResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetAmountToPay" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Preview the amount to pay for postpaid usage in the current billing period.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_GetAmountToPayReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getAmountToPay<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_GetAmountToPayReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetAmountToPayResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getAmountToPay(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_GetAmountToPayReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_GetAmountToPayResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AnalyzeBillingItems" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get historical usage of the API over a time period, aggregated by fields.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_AnalyzeBillingItemsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func analyzeBillingItems<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_AnalyzeBillingItemsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Prod_ClickhouseAnalytics_AnalyticsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.analyzeBillingItems(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_AnalyzeBillingItemsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Prod_ClickhouseAnalytics_AnalyticsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListInvoices" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List invoices that belong to a team.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_ListInvoicesReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listInvoices<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_ListInvoicesReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListInvoicesResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listInvoices(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_ListInvoicesReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_ListInvoicesResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListPrepaidBalanceChanges" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List the prepaid credit balance and balance changes of a team.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_ListPrepaidBalanceChangesReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listPrepaidBalanceChanges<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_ListPrepaidBalanceChangesReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListPrepaidBalanceChangesResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listPrepaidBalanceChanges(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_ListPrepaidBalanceChangesReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_ListPrepaidBalanceChangesResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TopUpOrGetExistingPendingChange" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Top up prepaid credit using the default payment method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_TopUpOrGetExistingPendingChangeReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func topUpOrGetExistingPendingChange<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_TopUpOrGetExistingPendingChangeReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_TopUpOrGetExistingPendingChangeResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.topUpOrGetExistingPendingChange(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_TopUpOrGetExistingPendingChangeReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_TopUpOrGetExistingPendingChangeResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetSpendingLimits" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get the postpaid monthly spending limits. The API will stop functioning once the team has consumed all of the
    /// > prepaid credits, and the postpaid usage amount has reached the user-set soft spending limit.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_GetSpendingLimitsReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getSpendingLimits<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_GetSpendingLimitsReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetSpendingLimitsResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getSpendingLimits(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_GetSpendingLimitsReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_GetSpendingLimitsResp>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetSoftSpendingLimit" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Set the postpaid monthly spending limit of a team. This can be used to restrict the maximum amount of postpaid API
    /// > usage. Note this will not limit the amount of prepaid credit usage, and prepaid credits will always be consumed
    /// > before accruing postpaid usage. To use only prepaid credits, you can set this limit to 0.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ProdMcBilling_SetSoftSpendingLimitReq` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setSoftSpendingLimit<Result>(
        request: GRPCCore.ClientRequest<ProdMcBilling_SetSoftSpendingLimitReq>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetSoftSpendingLimitResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.setSoftSpendingLimit(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ProdMcBilling_SetSoftSpendingLimitReq>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ProdMcBilling_SetSoftSpendingLimitResp>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension ProdMcBilling_UISvc.ClientProtocol {
    /// Call the "SetBillingInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Set billing information of a team.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setBillingInfo<Result>(
        _ message: ProdMcBilling_SetBillingInfoReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetBillingInfoResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_SetBillingInfoReq>(
            message: message,
            metadata: metadata
        )
        return try await self.setBillingInfo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetBillingInfo" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get billing information of the team with given team ID.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getBillingInfo<Result>(
        _ message: ProdMcBilling_GetBillingInfoReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetBillingInfoResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_GetBillingInfoReq>(
            message: message,
            metadata: metadata
        )
        return try await self.getBillingInfo(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListPaymentMethods" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List payment methods of a team. You can add or delete the payment methods on https://console.x.ai.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listPaymentMethods<Result>(
        _ message: ProdMcBilling_ListPaymentMethodsReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListPaymentMethodsResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_ListPaymentMethodsReq>(
            message: message,
            metadata: metadata
        )
        return try await self.listPaymentMethods(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetDefaultPaymentMethod" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Set default payment method to an existing payment method on file.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setDefaultPaymentMethod<Result>(
        _ message: ProdMcBilling_SetDefaultPaymentMethodReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetDefaultPaymentMethodResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_SetDefaultPaymentMethodReq>(
            message: message,
            metadata: metadata
        )
        return try await self.setDefaultPaymentMethod(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetAmountToPay" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Preview the amount to pay for postpaid usage in the current billing period.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getAmountToPay<Result>(
        _ message: ProdMcBilling_GetAmountToPayReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetAmountToPayResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_GetAmountToPayReq>(
            message: message,
            metadata: metadata
        )
        return try await self.getAmountToPay(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AnalyzeBillingItems" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get historical usage of the API over a time period, aggregated by fields.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func analyzeBillingItems<Result>(
        _ message: ProdMcBilling_AnalyzeBillingItemsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Prod_ClickhouseAnalytics_AnalyticsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_AnalyzeBillingItemsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.analyzeBillingItems(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListInvoices" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List invoices that belong to a team.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listInvoices<Result>(
        _ message: ProdMcBilling_ListInvoicesReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListInvoicesResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_ListInvoicesReq>(
            message: message,
            metadata: metadata
        )
        return try await self.listInvoices(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListPrepaidBalanceChanges" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > List the prepaid credit balance and balance changes of a team.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listPrepaidBalanceChanges<Result>(
        _ message: ProdMcBilling_ListPrepaidBalanceChangesReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_ListPrepaidBalanceChangesResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_ListPrepaidBalanceChangesReq>(
            message: message,
            metadata: metadata
        )
        return try await self.listPrepaidBalanceChanges(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TopUpOrGetExistingPendingChange" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Top up prepaid credit using the default payment method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func topUpOrGetExistingPendingChange<Result>(
        _ message: ProdMcBilling_TopUpOrGetExistingPendingChangeReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_TopUpOrGetExistingPendingChangeResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_TopUpOrGetExistingPendingChangeReq>(
            message: message,
            metadata: metadata
        )
        return try await self.topUpOrGetExistingPendingChange(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetSpendingLimits" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Get the postpaid monthly spending limits. The API will stop functioning once the team has consumed all of the
    /// > prepaid credits, and the postpaid usage amount has reached the user-set soft spending limit.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getSpendingLimits<Result>(
        _ message: ProdMcBilling_GetSpendingLimitsReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_GetSpendingLimitsResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_GetSpendingLimitsReq>(
            message: message,
            metadata: metadata
        )
        return try await self.getSpendingLimits(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SetSoftSpendingLimit" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Set the postpaid monthly spending limit of a team. This can be used to restrict the maximum amount of postpaid API
    /// > usage. Note this will not limit the amount of prepaid credit usage, and prepaid credits will always be consumed
    /// > before accruing postpaid usage. To use only prepaid credits, you can set this limit to 0.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func setSoftSpendingLimit<Result>(
        _ message: ProdMcBilling_SetSoftSpendingLimitReq,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<ProdMcBilling_SetSoftSpendingLimitResp>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ProdMcBilling_SetSoftSpendingLimitReq>(
            message: message,
            metadata: metadata
        )
        return try await self.setSoftSpendingLimit(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}